// GENERATED by twine-mcp-server `npm run export-ink` from sizzle/src/content/blackout.twee.
// Phase 1 bulk conversion — conventions: sizzle/docs/godot/INK-CONVENTIONS.md.
// Hand-edits must be recorded in sizzle/docs/godot/PHASE-1-CONVERSION-REPORT.md.

INCLUDE mirror.ink
INCLUDE ops.ink

// Story-local narrative state (not mirrored; ink may assign freely).
VAR blk_skill_granted = false
VAR blk_climbed = false
VAR blk_influence_granted = false

-> BLK_085

// The hottest day of the year
=== BLK_085 ===
# id: BLK_085
# avatar: blk_day
~ set_date(2003, 8, 14, "afternoon")
~ set_header("THE DANFORTH, TORONTO", "Thursday afternoon")
The hottest week of the year has saved its worst for today. Thirty degrees, and the humidity on top. Whoever said Canada was cold never came to Toronto in the middle of the summer.  Nobody's moving faster than they have to.
{
- background == "RCMP constable":
    You've spent three days at a policing-conference downtown and seen too many people and not enough sky. The afternoon session let out early, and you and the other attendees under 30 — all three of you — turned east without deciding to. You all needed a beer, and The Danforth was as good a place as any to get one.
- background == "CSIS analyst":
    You've spent three days at an intelligence-analysis forum in the city, and thankfully the afternoon panel was done by three. You'd been in meetings since seven and you heard there were good Greek restaurants on The Danforth, but all you can muster the energy for is a beer.
- background == "grad student":
    You'd brought a stack of assignments to East Lynn Park and the idea of marking them in the shade somewhere. You managed two pages before the heat made concentration feel optional.  You need a beer.
- else:
    No particular reason to be on The Danforth. No particular reason to be much of anywhere, these days. You need a beer.
}
* [The bar is half a block ahead, and it almost certainly has a fan.] -> BLK_090

// Up the Danforth
=== BLK_090 ===
# id: BLK_090
# avatar: blk_day
~ set_header("THE DANFORTH, TORONTO", "Thursday afternoon")
The strip does its usual August business: Greek diners with awnings out, the smell of souvlaki from the ventilation, a fruit stand with its crates going soft in the heat, a kid on a bike clipping the parked cars. The 504 streetcar runs past, overhead wire humming, in no more hurry than anyone else.  Less if you're being honest.
{
- background == "RCMP constable":
    There are so many people around. The [url=gloss:Sault]Soo[/url] isn't tiny by any means, but it's a whole different beast from Toronto. It feels overwhelming.
- background == "CSIS analyst":
    You clock patterns without meaning to. Who's moving fast, who's stopped. You wonder if becoming an analyst has somehow fundamentally broken you.
- background == "grad student":
    Ordinary Thursday afternoon. The street gives you an excuse to ignore your grading.
- else:
    Nobody's in a hurry. That suits you.
}
* [The bar's door is a few steps ahead, and through the glass it looks mercifully dark.] -> BLK_095

// Somewhere with a fan
=== BLK_095 ===
# id: BLK_095
# avatar: blk_day
~ set_header("BAR, THE DANFORTH", "Thursday afternoon")
The door swings shut behind you and the heat drops about five degrees. Not cool, but survivable. It takes your eyes a few moments to adjust, but when they do you can see the bar is a low-lit room: vinyl stools, a mirror behind the bottles, two ceiling fans doing their best. A handful of people. The bartender gives you the nod. Older, but still a hipster with a moustache.
You take the room in before you take a seat. Bar on the right, washrooms at the back, the patio door propped open to the lane. Cool enough that you could sit here a while.
* [You settle in.] -> BLK_100

// Last call before dark
=== BLK_100 ===
# id: BLK_100
# avatar: blk_day
~ set_header("BAR, THE DANFORTH", "Thursday afternoon")
Quickly you get a beer in front of you, and it's cold enough that the glass is sweating. Perfect.
{
- background == "RCMP constable":
    Two other younger constables from the conference are at the end of the bar, Robichaud and someone from Sudbury. You're half listening. After three days of seminar rooms, the silence of your own thoughts is welcome.
- background == "CSIS analyst":
    You're alone, which is what you wanted. The analysts from the forum are back at the hotel writing their summary notes. Fuck that.  It's too hot for notes.
- background == "grad student":
    Your thesis notes are open on the table, barely touched. Too hot to read at home, and the bar at least has beer, so here you are, approximately working.
- else:
    One beer, slowly. You're pretending this is lunch and pretending that you aren't a few weeks away from missing rent. Maybe the bar is hiring.
}
The heat comes off you in waves. You're not uncomfortable exactly. You're not much of anything, right now.
* [You stay a while.] -> BLK_105

// You don't even smoke
=== BLK_105 ===
# id: BLK_105
# avatar: blk_day
~ set_header("BAR, THE DANFORTH", "Thursday afternoon")
There's a book of matches on the bar, the bar's own, a logo you'll forget. You pick it up. Turn it over. Put it in your pocket.
You don't smoke. You don't know why you did that.
* [The afternoon goes on.] -> BLK_110

// Four-eleven
=== BLK_110 ===
# id: BLK_110
# avatar: blk_day
~ set_header("BAR, THE DANFORTH", "Thursday afternoon")
4:11 p.m.
The ceiling fans stop.
The cooler behind the bar makes a death rattle and then makes no sound at all. The radio cuts. The neon beer sign above the mirror goes dark. Outside, through the patio door, the traffic light at the corner cycles off and stays off.
Somebody at the bar says: "Did you just —"
Somebody else says: "Yeah."
The bartender looks at the ceiling. Looks at the bottles. Looks at the ceiling again.
* [Nobody moves for a moment.] -> BLK_115

// Warm beer and a radio
=== BLK_115 ===
# id: BLK_115
# avatar: blk_day
~ set_header("BAR, THE DANFORTH", "Thursday afternoon")
The bartender finds a candle behind the bar, the half-used emergency kind, and lights it. Someone's transistor radio coughs static, then a voice that won't commit to much: not just the block, not just the neighbourhood.
The bar settles into the strange intimacy of a blackout: lower voices, people looking at each other differently.
{
- background == "RCMP constable":
    Robichaud's talking about the walk back to the hotel; the Sudbury constable's with him. You stay for one more.  You stick around with the offhand hope that the power will be back on after another beer and you can avoid the two-hour walk in the heat back downtown.  Or maybe Robichaud's just annoying and you think he's trying to get in your pants.  Maybe on a day when it isn't so hot.
- background == "CSIS analyst":
    Even if the radio won't say it, you know the score. Every light on the strip died on the same instant. Not a blown transformer, not a line down in a storm; something let go a long way upstream of here. Whatever it is, it's well above your pay grade, and it won't be fixed before all the beer here is warm. You settle up and go.
- else:
    You settle up and leave before the beer gets warm.
}
* [Outside, the city is waiting.] -> BLK_120

// Walking home in the heat
=== BLK_120 ===
# id: BLK_120
# avatar: blk_day
~ set_header("THE DANFORTH, TORONTO", "Thursday afternoon")
The [url=gloss:TTC]TTC[/url] is dead: no streetcars, no subway, not even buses. The whole city is on foot, moving in the same direction, which is home. You join it.
Out here the dark is downright sociable. Stranger than a normal evening, and friendlier than it ought to be. People are talking to each other at intersections. Someone has walked their car into the middle of the road to wave traffic through.  Some dude is playing a guitar on a corner.
Thirty degrees in the shade, and the shade has moved east. There's no hurry because there's no other option. You walk.
* [The walk will take a while.] -> BLK_125

// The city helping itself
=== BLK_125 ===
# id: BLK_125
# avatar: blk_day
~ set_header("THE DANFORTH, TORONTO", "Thursday afternoon")
A man in a dress shirt is directing traffic at a dead intersection. He has no vest, no authority, and excellent hand signals. A restaurant owner is carrying chairs out to the sidewalk so the people walking by have somewhere to sit. Three neighbours are on a stoop sharing something from a bag, chips maybe, watching the foot traffic like it's a parade.
{
- background == "RCMP constable":
    You note who's calm, who's useful, who's going to be a problem by midnight if the power stays out. It's honestly far more chill than you would have expected from the big city.
- background == "CSIS analyst":
    You read the crowd the way the job taught you. Everyone seems chill. You aren't worried about it being a problem.
- background == "grad student":
    Your thesis is about coercive persuasion, but this is its opposite: a crowd that has made a collective decision to not fall apart.
- else:
    You've walked through worse. This feels more like a party than a panic.
}
* [The walk continues.] -> BLK_130

// The propped door
=== BLK_130 ===
# id: BLK_130
# avatar: blk_day
~ set_header("JUST OFF THE DANFORTH", "Thursday afternoon")
You head up a side street to find some better shade. A few blocks in, a [url=gloss:walkup]walkup[/url] catches your eye. The front door is open.
The walkup is three stories, ten or twelve units, built in the 1940s or 1950s and maintained ... moderately. The street-side door is propped open with a brick. Through the gap comes sound.
Not ordinary building sound. Not a TV through a wall, not a neighbour's argument. Something lower and sustained. A sensual moan that lands wrong in your chest.
You stop.
* [You push the door open a little wider and look in.] -> BLK_135
* [You keep walking.]
    Half a block. Maybe a little more. The sound follows you. Or it doesn't, exactly, but the memory of it does, and it won't shake loose. At the corner your feet slow before you do. You look back. The door is still propped. Whatever that sound was is still wrong.
    * * [You cross back to the propped door.] -> BLK_135

// Crossing the little yard
=== BLK_135 ===
# id: BLK_135
# avatar: blk_day
~ set_header("WALKUP, JUST OFF THE DANFORTH", "Thursday afternoon")
Between the sidewalk and the door there's a small concrete yard: a bike against the railing, a planter dried out from the week, a scorch mark where someone used to barbecue. Normal. All of it normal.
Through the gap: a dim hallway, the suggestion of a mailbox row, and the smell of someone's dinner gone cold on a stove.
Normal. Yet your unease has sharpened.
* [You go inside.] -> BLK_140

// The lobby — # check protocol knot
=== BLK_140 ===
# id: BLK_140
# avatar: blk_night
# check: composure/streetwise 2d6 7
~ set_time("evening")
~ set_header("WALKUP LOBBY", "Thursday evening")
The lobby is a short hallway: mailboxes on one wall, a fire extinguisher on the other, emergency lighting running off its battery pack in a dim orange arc. The smell: stale carpet, old cooking, heat that has been indoors too long.
The stairwell at the end of the hall is dark. Too dark.
It's not dark the way the rest of the city is dark. Darker. The light from outside reaches the bottom stair and stops, and what's beyond that point is a different quality of dark entirely. A darkness that's almost physical.
{ check_passed:
    It's not the power being out. You've been walking through powerless dark all evening and none of it felt like this. You look up and see that this stairwell has been illuminated by a broad lobby light. Probably been bathed in light for years. Maybe that light was keeping something away.
    * [You step further into the lobby.] -> BLK_145
- else:
    You don't have a framework for it. There's just the dread, the animal certainty that something at the top of those stairs is not what it should be. You feel it in your throat before anywhere else.
    * [You step further into the lobby.] -> BLK_145
}

// The man who won't go up
=== BLK_145 ===
# id: BLK_145
# avatar: blk_night
~ set_header("WALKUP LOBBY", "Thursday evening")
A heavy-set man in his fifties pokes his head out from a first floor unit, watching the stairwell the way you are.
"Don't go up," he says.
* [You ask if he knows what's happening.]
    He's quiet for a moment. "Light's been on since I moved in. Five years. Never went out." He nods toward the stairwell. "Now it has."
    He goes back inside. You hear his deadbolt.
    * * [You stand in the lobby with that.] -> BLK_150

// What the dark is doing
=== BLK_150 ===
# id: BLK_150
# avatar: blk_night
~ set_header("WALKUP LOBBY", "Thursday evening")
The woman comes out from a doorway right next to the stairwell; you hear the door, then her on the stairs. She's in her mid-thirties, wearing a sundress, one strap slipping off her shoulder. She's looking up the stairwell, not at you.
She's also undoing the dress as she walks. It slips off her body by the time she reaches the edge of the light. She's naked underneath.
She didn't even register that you were there, and now she's climbing into the dark above completely nude.
As she disappears into the darkness you hear her footsteps continue up.
* [You watch the dark where she went.] -> BLK_155

// The sound from above
=== BLK_155 ===
# id: BLK_155
# avatar: blk_night
~ set_header("WALKUP LOBBY", "Thursday evening")
From above: sounds you can't mistake. Not one person's sounds. Several. They are very clearly fucking. Loudly. Groups of them. In the dark.
A shape moves across the top of the stairwell, a silhouette pressed against another, mouths finding each other in the dark.
You're warm and not from the heat. A low pulse that quickens between your legs with the sounds above.
Whatever is up those stairs terrifies you. You're also sure something deep within you wants to go up there.
* [You haven't moved.] -> BLK_160

// The pull — # check protocol knot
=== BLK_160 ===
# id: BLK_160
# avatar: blk_night
# check: composure 2d6 8
~ set_header("WALKUP LOBBY", "Thursday evening")
The dark wants you in it. Part of you is ready to go.
Your feet haven't moved. Yet.
{ check_passed:
    { not blk_skill_granted:
        ~ grant_skill("composure", 1)
        ~ blk_skill_granted = true
    }
    ~ blk_climbed = false
    Your feet stay. The want is real, but the part of you that decides is holding at the line, watching the rest of you strain toward the dark.
    * [You hold your position.] -> BLK_165
- else:
    ~ blk_climbed = true
    Your foot finds the first stair.
    * [You take a step.] -> BLK_165
}

// Two steps up
=== BLK_165 ===
# id: BLK_165
# avatar: blk_night
~ set_header("WALKUP STAIRWELL", "Thursday evening")
{ blk_climbed:
    Two steps up. Maybe three. The dark on the stairs is thicker than the lobby dark, and warmer, and the moment you crossed the bottom stair the want changed. Louder. More definite. Something that was background noise a breath ago, now with your name on it.
    Your hand is around the matchbook in your pocket.
    You don't know if you put it there on purpose. You stop taking steps.
- else:
    You don't go. Some part of you draws the line here, at the bottom stair, and holds it.
    The want is still there. But you hold.
}
* [You turn your attention to the dark itself.] -> BLK_170

// It's the dark itself — # check protocol knot
=== BLK_170 ===
# id: BLK_170
# avatar: blk_night
# check: academic 2d6 7
~ set_header("WALKUP LOBBY", "Thursday evening")
The man downstairs said the light had been on for five years. Maybe it was holding something back.
A thing in the dark. Maybe the dark itself is a thing.
{ check_passed:
    { not blk_skill_granted:
        ~ grant_skill("academic", 1)
        ~ blk_skill_granted = true
    }
    You reason it through, which is what you do. If the light keeps the dark manageable, introducing light interrupts whatever the dark has become. Practical. Testable. Your hand is already moving.
    * [You think of the matchbook.] -> BLK_175
- else:
    You don't reason it. There isn't time and the dark is still pulling. Your hand finds the matchbook before the thought does.
    * [Your hand closes around the matchbook.] -> BLK_175
}

// The matchbook
=== BLK_175 ===
# id: BLK_175
# avatar: blk_night
~ set_header("WALKUP LOBBY", "Thursday evening")
{ not blk_skill_granted:
    ~ grant_skill("streetwise", 1)
    ~ blk_skill_granted = true
}
The matchbook in your hand. You don't smoke.
You tear off a match and strike it against the strip.
Nothing. The head skids and crumbles.
Above you, sounds. An ecstatic scream. The sound of wet flesh pounding into more wet flesh. The dark is patient.
You tear off another match.
* [You strike.] -> BLK_180

// One match
=== BLK_180 ===
# id: BLK_180
# avatar: blk_night
~ set_header("WALKUP LOBBY", "Thursday evening")
{ not blk_influence_granted:
    ~ adjust_influence(1)
    { blk_climbed:
        ~ adjust_influence(1)
    }
    ~ blk_influence_granted = true
}
It catches.
A small orange flame, not much bigger than a thumbnail. The stairwell eases the way a held breath eases. The dark recoils, like a predator that saw an opportunity and exposed too much of itself. It skitters away. Gone. Forever? For now at least. The want in your body steps down, then down again.
Above you, the sounds change. Confusion where a moment ago there was none. Someone says, distantly: "What — where —"
What do you do with the match?
* [You hold it up as high as your arm reaches.] -> BLK_185
* [You find a hallway votive on the window ledge and light it.] -> BLK_185
* [You fold a flyer from the mailbox rack into a torch and light it.] -> BLK_185

// The building exhales
=== BLK_185 ===
# id: BLK_185
# avatar: blk_night
~ set_header("WALKUP LOBBY", "Thursday evening")
From above: footsteps that are not the blank-faced climbing kind. Hesitation. A man's voice saying "oh god" in a way that does NOT sound ecstatic.
Then more of it. The sounds of people who don't know how they got where they're standing. The specific shame of not knowing why your clothes are undone, or where your phone is, or who the stranger next to you is.
Nobody comes downstairs. Not yet.
* [You don't wait to be seen.] -> BLK_190

// Before anyone thanks you
=== BLK_190 ===
# id: BLK_190
# avatar: blk_night
~ set_header("WALKUP, JUST OFF THE DANFORTH", "Thursday evening")
You back out the way you came in. Across the lobby, past the mailboxes, through the screen door, across the little yard. You don't look back.
The match has burned down to your fingers. You drop it on the concrete.
The street has moved on while you were inside. People still walking home, still directing traffic, still sharing chips on stoops. Normal. They don't know anything happened. Thirty metres away something was banished away, something you can't name, and the street never felt it.
* [You keep moving.] -> BLK_200

// The rest of the dark
=== BLK_200 ===
# id: BLK_200
# avatar: blk_night
~ set_header("TORONTO", "Thursday evening")
{background == "RCMP constable" or background == "CSIS analyst": The walk back to your hotel takes more than two hours.|The walk takes more than two hours, until you make it to your friend Genevieve's downtown condo to crash.} You don't try to make sense of it. You try to resync with the strangers walking beside you, the people who seem to be having a party despite having their evening ruined.
There was something wrong in that stairwell. You stopped it with those matches you shouldn't have had.
In the distance you can see the odd skyscraper or two with their lights on. Little twinkling points in the black of night.
* [You get home sometime after nine.] -> BLK_205

// Still out
=== BLK_205 ===
# id: BLK_205
# avatar: blk_day
~ advance_days(1, "morning")
~ set_header("TORONTO", "Friday morning")
Friday morning and the power is still out.
The city has settled into it: people on front porches with coffee, radio news through open windows, {background == "RCMP constable" or background == "CSIS analyst": the intersection outside your hotel still a mess|the intersection below Genevieve's building still a mess}. The radio reports Ontario Hydro saying power will probably be back today. Ontario Hydro said probably yesterday too.
You haven't told anyone about the walkup.
* [A week passes.] -> BLK_210

// Incident report — Branch file extract STUB (native scene template later)
=== BLK_210 ===
# id: BLK_210
# screen: menu
# scene: branch_file_extract
# extract: blk_incident_report_03_DAN_0814
~ set_date(2003, 8, 21, "morning")
~ set_header("BRANCH FILE EXTRACT", "Thursday morning")
Incident File 03-DAN-0814, extract. Rendered by the native BranchFileExtract scene template; this knot is a placeholder.
* [You turn the page.] -> BLK_215

// Recommendation — Branch file extract STUB (native scene template later)
=== BLK_215 ===
# id: BLK_215
# screen: menu
# scene: branch_file_extract
# extract: blk_recommendation_r_flett
~ set_header("BRANCH FILE EXTRACT", "Thursday morning")
Recruitment Recommendation, R. Flett, 2003.08.21. Rendered by the native BranchFileExtract scene template; this knot is a placeholder.
* [The file closes.]
    // TODO(runtime): native CC-500 handoff sets inciting_incident to "the Toronto Blackout"
    ~ set_date(2005, 9, 12, "morning")
    -> blk_end

// Native-scene handoff — original twee target(s): CC-500 Summary.
=== blk_end ===
# id: blk_end
The blackout sequence ends here; the runtime hands off to the native scene (CC-500 Summary).
-> END

