// GENERATED by twine-mcp-server `npm run export-ink` from sizzle/src/content/briefing.twee.
// Phase 1 bulk conversion — conventions: sizzle/docs/godot/INK-CONVENTIONS.md.
// Hand-edits must be recorded in sizzle/docs/godot/PHASE-1-CONVERSION-REPORT.md.
// Since SugarCube retirement (2026-07-11) this file is canonical and edited directly.
// EVAL_* knots (psych eval + prologue exit; sizzle/docs/PSYCH-EVAL-PLAN.md) are
// original ink content with no twee source.

INCLUDE mirror.ink
INCLUDE ops.ink

// Story-local narrative state (not mirrored; ink may assign freely).
VAR briefing_read_robert = false
VAR briefing_called_out = false
// Psych eval answers (EVAL_110..165). The persistent record goes to story_tags /
// kinks via ops at the choice; these locals only drive Caron's reactions.
VAR eval_sleep = ""
VAR eval_stays = ""
VAR eval_close = ""
VAR eval_watched = ""
VAR eval_out = ""
VAR eval_why = ""

-> INTRO_100

// Briefing
=== INTRO_100 ===
# id: INTRO_100
# mode: day
# history_root
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
// Scene state object — persists across passages (unlike $temp which resets)
// reset scene state ($briefing = {})
~ briefing_read_robert = false
~ briefing_called_out = false
The diner smells like coffee that's been on the burner since six and bacon grease that's been in the ventilation since before the [url=gloss:Diefenbunker]Diefenbunker[/url] was built.  A place on [url=gloss:Bank Street]Bank Street[/url] south of Gloucester, no sign worth reading, where the booths are brown vinyl and the light is the colour of weak tea.  Half the clientele are civil servants eating before the buildings open, career government workers worried that the minority Liberal parliament might lose a confidence vote.  Nobody looks at you twice, which is the point.
You're early.  You're always early for Robert.  Mostly because it pisses him off.  He loves you for it though.
* [Sip your coffee.] -> INTRO_101

// Waiting
=== INTRO_105 ===
# id: INTRO_105
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
The waitress brings coffee without being asked — you've been here before, enough times that she recognizes the booth but not your name.  Her name is Gladys.  You wrap your hands around the mug and watch the door.
Outside, an [url=gloss:OC Transpo]OC Transpo[/url] bus grinds past on [url=gloss:Bank Street]Bank[/url], throwing diesel haze across the sidewalk.  September in Ottawa.  Still warm, but the light has changed — that particular quality of autumn sun that makes the limestone go yellow.
{
- background == "RCMP constable":
    You used to drink coffee like this at the detachment — institutional, slightly burnt.  The ritual is the same even if the context has shifted.
- background == "CSIS analyst":
    You used to meet sources in places like this.  The tradecraft is the same.
- background == "grad student":
    There's a woman two booths over eating eggs alone and staring at nothing.  The part of your brain that studied behavioural patterns can't stop reading the room.  You look away.  Not a case study.
- else:
    Two years ago you wouldn't have known what to look for in a diner — the exits, the sightlines, the two men at the counter reading the same section of the Citizen.
}
* [Continue] -> INTRO_110

// Robert arrives
=== INTRO_110 ===
# id: INTRO_110
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
// [image] media/characters/robert-flett-diner-entry.png — native presentation TBD
Robert Flett arrives at 8:14, which means he was in the neighbourhood by 7:45 and spent the intervening time making sure he wasn't followed.  You know this because he taught you to do the same thing, and because he's carrying a copy of the [url=gloss:Globe]Globe[/url] that looks like it's already been read.  It's a ridiculous thing to do half a block from the office, but it's [i]because[/i] you're a known regular here — Robert dropping in once doesn't read as a meet.  You smile that he does the newspaper bit anyway.
He doesn't look like a man who tracks the inexplicable for a living.  He looks like a mid-level bureaucrat — brown skin you've long since placed as [url=gloss:Métis]Métis[/url], hair going grey at the temples, a jacket that's seen better years.  He grew up in [url=gloss:Shield country]Shield country[/url] between the [url=gloss:Sault]Sault[/url] and [url=gloss:Thunder Bay]Thunder Bay[/url].
* [The one thing that doesn't match is his hands.] -> INTRO_115

// Morning
=== INTRO_115 ===
# id: INTRO_115
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
Working hands, scarred across the knuckles.  You noticed them the first day you met him, two years ago, and you still don't know the story.  Especially since you do know the story of how he was an academic at [url=gloss:Lakehead]Lakehead[/url] and a star grad student at [url=gloss:U of T]U of T[/url].  But who knows what he's seen in the dark of the woods.
He slides into the booth across from you, sets the [url=gloss:Globe]Globe[/url] on the table, and catches the waitress's eye.  Coffee.  No food yet.
"Morning," he says.
* ["Morning."] -> INTRO_200
* ["You look tired."] -> INTRO_200a

// Personal
=== INTRO_200a ===
# id: INTRO_200a
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
He gives you a look and a smile.  "Well fuck you too, junior."  He takes the coffee from the waitress, adds one cream, stirs it exactly three times.  Same as always.
No folder this time, no laptop.  Robert looks at you for a moment with that particular expression he gets when he's about to tell you something he's been thinking about for a while.
"I have an assignment for you," he says.  "Your first sustained field placement."
* [The weight of those words settles over the table.] -> INTRO_205

// Assignment
=== INTRO_200 ===
# id: INTRO_200
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
He nods.  Takes the coffee from the waitress, adds one cream, stirs it exactly three times.  Same as always.
No folder this time, no laptop.  Robert looks at you for a moment with that particular expression he gets when he's about to tell you something he's been thinking about for a while.
"I have an assignment for you," he says.  "Your first sustained field placement."
* [The weight of those words settles over the table.] -> INTRO_205

// Field placement
=== INTRO_205 ===
# id: INTRO_205
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
He pauses.  Two years of training, two years of reading case files and attending seminars on [url=gloss:NYSE]NYSE[/url] classification protocols and learning to shoot at a range in Carp that the [url=gloss:Branch]Branch[/url] pretends is a conservation club.
This is what it was for.
"There's a club on Queen West," he says.
Huh, Toronto.  That's odd.  Most NYSE incidents are further north.  Also, a Toronto field placement is a plum assignment — someone more senior would surely be fighting for it.  There must be a catch.
"Members-only.  Been operating for about two years.  Called Sizzle."
He says the name without inflection, like it's a case number.
"It's a swingers club."
Ah, there it is.
* [You raise an eyebrow.] -> INTRO_210

// Swingers club
=== INTRO_210 ===
# id: INTRO_210
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
Another pause.  Robert is very good at pauses.  But so are you.
"The [url=gloss:Branch]Branch[/url] has been tracking anomalous reports associated with the club and its membership for the past fourteen months.  Behavioural changes in regular members — progressive, directional, consistent enough to flag [url=gloss:NYSE]NYSE[/url] classification."
He takes a sip of coffee.  Puts the mug down.
"We don't have anyone inside.  We need someone inside."
No shit, Bob.
* ["What kind of anomalous?"] -> INTRO_300
* ["What's my cover?"] -> INTRO_310
* ["A swingers club."] -> INTRO_320

// NYSE details
=== INTRO_300 ===
# id: INTRO_300
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
Robert turns his coffee mug a quarter rotation.  He does this when he's choosing his words.
"Influence patterns," he says.  "Members who've been attending regularly show progressive changes in behaviour and personality.  Not sudden — gradual.  Each step looks like a natural extension of the one before it.  A person who was relatively conservative six months ago is now doing things they wouldn't have imagined a year prior."
Another pause.  "Ass fisting," he says dryly.
You raise an eyebrow.  He almost grins.  He's giving you shit.
"The escalation is the signature."
* [Continue] -> INTRO_305

// NYSE continued
=== INTRO_305 ===
# id: INTRO_305
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
"We've also picked up reports of intrusive ideation.  Desires that feel implanted rather than organic.  Attraction to specific individuals that doesn't match established patterns.  Some reports of altered time perception inside the club.  Memory inconsistencies."
{ background == "CSIS analyst":
    You recognize the briefing structure — he's presenting the indicators without the conclusion, letting you draw it yourself.  An analyst's habit.
}
"Everything we have is secondhand.  A therapist.  A spouse.  An acquaintance we recruited.  The members themselves don't know they're being observed."
He meets your eyes.  "Which is why we need primary observation."
* ["What's actually causing it?"] -> INTRO_330
* ["Walk me through the operational setup."] -> INTRO_400

// Cover
=== INTRO_310 ===
# id: INTRO_310
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
He almost smiles.  Almost.
"Straight to operational.  Good."  He shifts in the booth, leaning forward slightly — the shift from briefing officer to handler.
"The cover is employment.  You're going to get a job at Sizzle.  Not as a member — as staff.  Bartender, hostess, coat check — whatever they're hiring for.  The Branch will set you up with an apartment in the neighbourhood, a backstory, documents."
"Nothing suspicious about a young woman wanting a job at a bar."
* [Continue] -> INTRO_315

// Cover continued
=== INTRO_315 ===
# id: INTRO_315
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
"The objective is access.  Get inside, observe, report.  Build relationships with staff and regular members.  Watch for anything that matches the [url=gloss:NYSE]NYSE[/url] indicators."
He leans back.
"The secondary objective — the reason we're not sending someone from Metro Police — is that you have [url=gloss:NYSE]NYSE[/url] training.  You know what to look for and, more importantly, you know what it feels like when something isn't right."
* ["What kind of anomalous reports are we talking about?"] -> INTRO_300
* ["Why me specifically?"] -> INTRO_340
* ["What are the risks?"] -> INTRO_400

// Reaction
=== INTRO_320 ===
# id: INTRO_320
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
You say it flat.  The words sit between you on the table.
Robert doesn't blink.  "A swingers club.  Members-only, well-established, well-regarded within its community.  Not a front.  A functioning club with a real membership, real events, real —" he pauses — "activities.  That is the operational environment."
There's a silence.  The waitress passes with a pot of coffee.  Somewhere in the kitchen, someone drops a plate and swears in Greek.
* ["Walk me through it."] -> INTRO_325
* ["I'm not doing it."] -> INTRO_322

// No concerns
=== INTRO_325 ===
# id: INTRO_325
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
"The assignment is intelligence-gathering in a sexually explicit environment," Robert says.  "That is what it is.  The [url=gloss:NYSE]NYSE[/url] element is why it's Branch instead of Vice.  If you have concerns about the nature of the work, this is the time to raise them."
{
- background == "grad student":
    You wrote a thesis chapter on environments like this — the social dynamics, the consent frameworks, the group psychology.
- background == "unemployed after university":
    You've been in places like this.  Not as an agent — as a person.  That's a different kind of knowledge.
}
* ["No concerns.  Walk me through it."] -> INTRO_400
* ["What kind of anomalous reports are we talking about?"] -> INTRO_300
* ["Why me specifically?"] -> INTRO_340

// Source
=== INTRO_330 ===
# id: INTRO_330
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
Robert is quiet for a moment.  It's a different quiet than his briefing pauses.
"We don't know," he says.  And then, because he's Robert: "The [url=gloss:Branch]Branch[/url] has classified the source as undetermined.  Current working hypotheses include an individual or individuals with anomalous capabilities, an environmental factor, or a combination."
He picks up his coffee, looks at it, puts it back down.
"In my experience —" he starts, then catches himself.  Starts again with the government version.  "In cases with this profile, there's usually a focal point."
* [Continue] -> INTRO_335

// Focal point — # check protocol knot
=== INTRO_335 ===
# id: INTRO_335
# mode: day
# check: academic 2d6 8
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
"Something or someone that's generating the effect.  Finding that focal point is part of what you'll be looking for."
{ check_passed:
    You catch the shift.  [i]In my experience.[/i]  Robert has seen cases like this before.  He was going to say something from that experience, and then he put the government language back on.
    You file that away.
    "But that's secondary to primary observation," he says, back on firm procedural ground.  "Your first priority is establishing cover and reporting what you see.  Don't go looking for the source.  Let the picture come to you."
    * ["Understood.  Walk me through the operational setup."] -> INTRO_400
- else:
    Whatever Robert almost said disappears back into the briefing.  You can feel the gap in the answer, but not what was behind it.
    "But that's secondary to primary observation," he says, back on firm procedural ground.  "Your first priority is establishing cover and reporting what you see.  Don't go looking for the source.  Let the picture come to you."
    * ["Understood.  Walk me through the operational setup."] -> INTRO_400
}

// Why me
=== INTRO_340 ===
# id: INTRO_340
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
Robert's expression doesn't change, but something behind it shifts — a microsecond of professional discomfort.
"The assignment requires a credibly attractive woman under thirty who has completed [url=gloss:Branch]Branch[/url] [url=gloss:NYSE]NYSE[/url] training and can sustain a cover identity in a high-pressure social environment."  He says this like he's reading it from a personnel form.  "The talent pool matching those criteria is small."
He takes three deliberate sips of coffee to put space between the clinical assessment and whatever comes next.
You've known Robert a while now.  This is maybe the first time you can remember when he isn't meeting your eyes.
* [Continue] -> INTRO_345

// Qualified
=== INTRO_345 ===
# id: INTRO_345
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
"You're good at reading people.  You can hold a conversation and a cover simultaneously.  You don't rattle easily.  And you understand [url=gloss:NYSE]NYSE[/url] classification well enough to recognize indicators in the field."
{
- background == "grad student":
    You studied persuasion and influence for two years.  You know when someone is framing a limited choice as a compliment.  Right now, Robert is not saying: [i]and I don't have anyone else.[/i]
- background == "RCMP constable":
    Three years of reading people on traffic stops and domestic calls taught you when someone is leaving something out.  Robert means everything he just said.  He also means something he didn't say.
- else:
    You read the obvious answer around his list of qualifications.  The Branch doesn't have many options, and you're the best one.
}
"I wouldn't send you if I didn't think you could do it," he adds.  Quieter.  Not government anymore — Robert.
* ["Walk me through the operational details."] -> INTRO_400

// Apartment
=== INTRO_400 ===
# id: INTRO_400
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
Robert reaches into his jacket and pulls out a single sheet of paper, folded twice.  He unfolds it on the table between the coffee mugs.  An address, a phone number, a short list in his careful handwriting.
"Operational details," he says, and now he's all handler.
"The Branch is setting up an apartment for you in Parkdale — close enough to the club to be plausible, far enough to not be conspicuous.  You'll have it by Wednesday.  Furnished, first and last covered through a shell company.  Cover name and documents will be ready by then."
* [Continue] -> INTRO_405

// Reporting
=== INTRO_405 ===
# id: INTRO_405
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
He taps the paper.
"You'll report to me directly.  Once a week to start, in-person, locations rotate.  If you need me urgently, there's a contact protocol — I'll walk you through it at the office."
He holds your gaze.
"If your cover is compromised — if someone at the club identifies you as Branch or law enforcement — you walk out.  Immediately.  You do not try to recover the cover.  You leave, you go to a pre-arranged location, and you wait for extraction."
* [Continue] -> INTRO_410

// Rules
=== INTRO_410 ===
# id: INTRO_410
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
"One more thing.  Don't go looking for the [url=gloss:NYSE]NYSE[/url] directly.  Don't break cover to investigate.  Be patient.  You're there to observe and report.  The analysis happens on this end."
He folds his hands on the table.
"Your job is to be a reliable pair of eyes inside that building."
{ INTRO_340 == 0:
    He pauses.  "You haven't asked why you."
    He doesn't wait for you to answer.
    "The assignment requires a credibly attractive woman under thirty who has completed [url=gloss:Branch]Branch[/url] training and can hold a cover.  The talent pool matching those criteria is small.  I want you to have heard that out loud before you walk into that building."
    He looks at his coffee instead of at you.
}
* {INTRO_300 == 0} [Tell me more about the NYSE reports.] -> INTRO_500
* {INTRO_510 == 0} [Tell me more about the club itself.] -> INTRO_510
* {INTRO_520 == 0} [What's the risk assessment?] -> INTRO_520
* {INTRO_530 == 0} [Have you sent anyone in before?] -> INTRO_530
* {has_tag("Lived in Toronto") and INTRO_540 == 0} [I lived in Toronto for a few years.  What if someone recognizes me?] -> INTRO_540
* {has_tag("Northern Ontario") and INTRO_550 == 0} [Ugh, Toronto?] -> INTRO_550
* [Continue] -> INTRO_600

// Question NYSE
=== INTRO_500 ===
# id: INTRO_500
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
"Can you tell me more about the [url=gloss:NYSE]NYSE[/url] indicators?"
Robert takes a slow breath — the particular care he takes when Branch language has to carry weight it wasn't designed for.
"The pattern is escalation.  Members attending for six months or more show measurable personality shifts.  Progressive disinhibition.  Altered risk assessment.  And in several cases, desires that the subjects themselves describe as foreign.  'Not like me.'  That's a direct quote from an asset's notes."
He turns his coffee mug.
"And dreams.  Vivid, persistent, thematically consistent.  Several subjects reported dreaming about the club on nights they didn't attend."
* [Continue] -> INTRO_410

// Question club
=== INTRO_510 ===
# id: INTRO_510
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
"What do you know about the club itself?"
Robert nods — the question he expected first.
"Sizzle has been operating for approximately four years.  Heritage property, Victorian-era, corner lot.  Members-only, vetted entry.  Events several nights a week.  The membership is cross-sectional — professionals, creatives, some local names you'd recognize."
"The owner operates under the name Viktor Reeves.  Thin file — business registration, property records.  Nothing that triggers on its own.  The club runs clean on paper."
"Which is either good management or a very effective front.  That's what you're going to find out."
* [Continue] -> INTRO_410

// Question risk
=== INTRO_520 ===
# id: INTRO_520
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
"What's the risk assessment?"
"Moderate to high," Robert says, without the usual bureaucratic hedging.  "The [url=gloss:NYSE]NYSE[/url] element makes it unpredictable.  Prolonged exposure represents a genuine cognitive risk.  You will be affected.  The question is degree."
He lets that sit.
"Composure training gives you tools.  It gives you awareness.  But there's a difference between understanding [url=gloss:NYSE]NYSE[/url] indicators in a briefing room and experiencing them in the field."  He pauses.  "In a club."
"The physical risk is lower.  The danger here is cognitive, not physical.  Which, in my experience, is harder to see coming."
* [Continue] -> INTRO_410

// Question previous — # check protocol knot
=== INTRO_530 ===
# id: INTRO_530
# mode: day
# check: composure 2d6 9
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
"Have you sent anyone in before?"
The pause is longer than usual.  Long enough that the waitress refills both your coffees and leaves before Robert speaks.
"No," he says.  "This is the Branch's first direct intelligence operation targeting Sizzle."
You wait.
"We considered it eighteen months ago.  The operational profile at the time didn't justify the risk.  It does now."
{ check_passed:
    He's telling the truth, but it's not the whole truth.  He's deciding whether to tell you the rest now or later.  He decides on later.
    "You'll be the first.  No playbook."
    * [Continue] -> INTRO_410
- else:
    You hear the answer and the careful pause after it.  If there is more behind the words, Robert keeps it locked down.
    "You'll be the first.  No playbook."
    * [Continue] -> INTRO_410
}

// Subtext
=== INTRO_600 ===
# id: INTRO_600
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
Robert folds the paper and slides it across the table to you.  "Wednesday, 10 AM, the office.  Full ops briefing, documents, keys."
He picks up his coffee and finishes it in one long pull.
And then there's a moment.
Just a small hitch in Robert's efficiency.  He puts the mug down and his hand stays on it for a beat too long, and he looks at you, and his expression is exactly the same as it always is, except —
* [Continue] -> INTRO_610

// Reading Robert — # check protocol knot
=== INTRO_610 ===
# id: INTRO_610
# mode: day
# check: composure 2d6 5
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
// Skill check: can the player read Robert's unease?
{ check_passed:
    ~ briefing_read_robert = true
    Except it isn't.
    You've sat across from this man in dozens of briefings.  You've learned his rhythms — the pauses, the mug rotations, the way he uses silence.  You know his resting face.
    And right now, under the steady professional surface, Robert Flett is worried.  Not about the operation.  He's worried about [i]you[/i].
    * ["You're worried about me."] -> INTRO_620
    * [Say nothing.  Let it pass.] -> INTRO_700
- else:
    Except — you're not sure.  There's something there, in the way he's holding the mug, but you can't quite read it.  Two years of training and you still can't always crack Robert Flett.
    Whatever it was, it passes.  He releases the mug and straightens in the booth.
    * [Continue] -> INTRO_700
}

// Called out
=== INTRO_620 ===
# id: INTRO_620
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
~ briefing_called_out = true
His eyes meet yours.  For a second — less than a second — the handler isn't there.  Just Robert, a man in his late forties who has been doing this work since before you were in high school, looking at someone he trained.
"I selected you for this assignment because you're the most qualified candidate available," he says.  And it's true.
"But yes."
Two words.  He doesn't elaborate.  He doesn't need to.
~ toast("info", "You saw through Robert's composure.  He trusts you enough to let you.")
* [Continue] -> INTRO_630

// Moment passes
=== INTRO_630 ===
# id: INTRO_630
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
The waitress comes by and asks if they want anything else.  Robert says no thank you and reaches for his wallet.
The moment is over.  It existed for exactly as long as it needed to.
* [Continue] -> INTRO_700

// Outside
=== INTRO_700 ===
# id: INTRO_700
# mode: day
~ set_header("Bank Street, Ottawa", "Monday morning")
Robert pays for both coffees — he always does, out of pocket, never expensed.  You noticed that about six months in and never mentioned it.
Outside, [url=gloss:Bank Street]Bank Street[/url] is doing what it does on a Monday morning.  Civil servants walking south toward the office towers with travel mugs and lanyards tucked inside their jackets.  A woman locking her bicycle to a rack outside a café that hasn't opened yet.
September sun on limestone.  Ottawa being unremarkably, specifically itself.
* [Continue] -> INTRO_710

// Last words
=== INTRO_710 ===
# id: INTRO_710
# mode: day
~ set_header("Bank Street, Ottawa", "Monday morning")
Robert stands on the sidewalk, hands in his jacket pockets.  He glances east, then west.  Old habit.
"Wednesday," he says.  "Ten o'clock.  Bring ID photos — two passport-style, one casual."
{briefing_read_robert: He pauses. Looks at you one more time with an expression that's almost the one from the diner. Then he straightens his shoulders and puts the handler back on.}"And {player_name}?"
You wait.
"Get some sleep this week.  You're going to want it."
* [Continue] -> INTRO_720

// Departure
=== INTRO_720 ===
# id: INTRO_720
# mode: day
~ set_header("Bank Street, Ottawa", "Monday morning")
He turns south, toward the office.  You watch him go — a man in an unremarkable jacket disappearing into the perfectly ordinary Monday morning.
{
- briefing_called_out:
    He's worried about you.  You're a little worried about you too.  But not enough to walk away — not after two years of getting ready for exactly this.
- briefing_read_robert:
    He's worried about you.  You wish you could tell him not to be.  But that would require a certainty you don't have.
- else:
    A new city, a new apartment, a new name.  A club on Queen West where something is happening that the Branch can't explain.  And you, walking into it with two years of training and a composure that hasn't been tested yet.
}
Wednesday.  Ten o'clock.  ID photos.
* [Your assignment begins.] -> EVAL_090

// End
=== INTRO_800 ===
# id: INTRO_800
# mode: day
End of Prologue
[i]To be continued — Act 1: Insertion[/i]
-> END

// Lost in thought
=== INTRO_101 ===
# id: INTRO_101
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
You aren't sure why Robert wanted to meet here instead of just at the office.  Despite the fact that you both worked in the field of the supernatural — sorry, the [url=gloss:NYSE]NYSE[/url] — all you'd done for the past two years since {inciting_incident != "": {inciting_incident}|the incident} was get trained.
Plucked out of your life as a {background != "": {background}|civilian}.  Your government agency didn't officially have a name (everyone just called it the [url=gloss:Branch]Branch[/url]), but it was still absolutely a government agency.  Meaning two years in you were still near the bottom of the pecking order — doing analysis, not going out into the field.
* [You rub your temples and let the thought go.] -> INTRO_105

// Concerns
=== INTRO_322 ===
# id: INTRO_322
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
"I'm not doing it."
Robert nods once.
"Understood."
He folds the paper before you've finished the sentence and slides it back into his jacket.  He finishes his coffee in two long pulls.
"I'll redirect you to the Vandermeer file when you're back at the office.  Foreign-publication review.  Three months out, minimum."
He stands, leaves a tip that's too generous for the bill, and pays at the till.  At the door he turns.
"You did the right thing telling me now."
He doesn't wait for an answer.
* [Begin again] -> intro_end

// Question recognized
=== INTRO_540 ===
# id: INTRO_540
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
"I lived in Toronto for a few years.  What if someone recognizes me?"
"Your cover will need to incorporate it.  Sadly, you'll have to go in under your own name."
{
- background == "unemployed after university":
    "Though from what I remember from your file, going to or working at a sex club won't be that big of a stretch for the people who knew you back then."
- background == "grad student":
    "It might be a bit surprising for people who knew you back then, but it wouldn't be that strange for a person to start expanding their horizons after a few years of being a real adult."
- else:
    "We'll workshop the cover with that in mind."
}
You just stare at him.
"Just try not to bump into anyone."
* [Continue] -> INTRO_410

// Question Toronto
=== INTRO_550 ===
# id: INTRO_550
# mode: day
~ set_header("Diner, Bank Street, Ottawa", "Monday morning")
"Ugh, Toronto?"
[i]Placeholder · Northern Ontario reaction.  Player's groan about being sent to the big city.  Robert deadpan reply.  Brief banter that lands as character, not info.[/i]
[i]To be written.[/i]
* [Continue] -> INTRO_410

// Native-scene handoff — original twee target(s): Start.
=== intro_end ===
# id: intro_end
The briefing sequence ends here; the runtime hands off to the native scene (Start).
-> END

// ============================================================================
// Psych eval + prologue exit (EVAL_090..210) — original ink content, no twee
// source. Design: sizzle/docs/PSYCH-EVAL-PLAN.md. Choices write the TRUTH to
// story_tags (a lie records the same flag as the honest answer); two answers
// seed kinks. The player is never shown any of this.
// ============================================================================

// Wednesday is paperwork
=== EVAL_090 ===
# id: EVAL_090
# mode: day
~ set_date(2005, 9, 14, "morning")
~ set_header("Branch office, Ottawa", "Wednesday morning")
Wednesday is paperwork. Two passport photos and one casual, like Robert asked — the photographer in the basement takes a fourth because the flash catches you blinking. Forms in triplicate for a cover identity you won't see assembled for another week. A woman from Documents studies your signature and asks you to make the loops smaller.
Robert appears at the end of it with a card in his hand.
"Tomorrow, ten o'clock. Across the street, fourth floor. Dr. Caron."
"Routine?"
"Routine." He buttons his jacket. "And they want to be sure about you. Both things are true."
* [You take the card.] -> EVAL_100

// The building across the street
=== EVAL_100 ===
# id: EVAL_100
# mode: day
~ set_date(2005, 9, 15, "morning")
~ set_header("O'Connor Street, Ottawa", "Thursday morning")
Across the street means across the street: from the lobby you can see your own office window. The directory lists an actuarial firm, two numbered companies, and a dentist. The fourth floor isn't listed.
The commissionaire signs you in without asking your name, which answers that question.
Upstairs the corridor smells of new carpet. One door stands open. The nameplate slot beside it is empty.
* [You knock on the open door.] -> EVAL_105

// Dr. Caron
=== EVAL_105 ===
# id: EVAL_105
# mode: day
~ set_header("Fourth floor, O'Connor Street", "Thursday morning")
She's on her feet before you're through the door, hand out, coffee already dripping through a filter cone on the windowsill.
"{player_name != "": {player_name}|Come in}. Denise Caron. Sit anywhere that isn't the good chair — the good chair is mine."
Forty-five or so. Cardigan over a silk blouse, reading glasses pushed up into grey-streaked hair, a wedding band she turns with her thumb when she listens. The office is rented furniture and one wall of her own books, brought in by the box.
"You know why you're here?"
"Clearance."
"Clearance," she agrees, pouring. "Everyone going long gets an hour with me. For you I asked for two. Milk, no sugar — that's right, isn't it?"
It is. You didn't tell her that.
* [You take the chair that isn't the good one.] -> EVAL_110

// SQ1 — sleep
=== EVAL_110 ===
# id: EVAL_110
# mode: day
~ set_header("Fourth floor, O'Connor Street", "Thursday morning")
She opens the folder but doesn't look at it. Behind her the window gives you the street, and across the street, the building where your desk is.
"Before the form. How are you sleeping?"
* ["Fine."]
    ~ eval_sleep = "fine"
    ~ add_tag("Sleeps fine")
    -> EVAL_115
* ["Badly. Since Monday, badly."]
    ~ eval_sleep = "badly"
    ~ add_tag("Sleeps badly")
    -> EVAL_115
* ["Fine," you lie.]
    ~ eval_sleep = "lie"
    ~ add_tag("Sleeps badly")
    -> EVAL_115

// Reaction — sleep
=== EVAL_115 ===
# id: EVAL_115
# mode: day
~ set_header("Fourth floor, O'Connor Street", "Thursday morning")
{
- eval_sleep == "fine":
    "Good." She writes nothing. "Keep whatever you're doing. Toronto will find its own ways to wreck it."
- eval_sleep == "badly":
    "Thank you for saying so." She writes one line. "It's the correct response, for what it's worth. The file they gave you would keep anyone up."
- else:
    "Good." She looks at you a half-second longer than the answer needs, then writes nothing.
}
She turns a page.
* [Continue] -> EVAL_120

// SQ2 — what stays
=== EVAL_120 ===
# id: EVAL_120
# mode: day
~ set_header("Fourth floor, O'Connor Street", "Thursday morning")
The page she turns to has a red jacket stapled inside — the incident report.
"I've read the file on {inciting_incident != "": {inciting_incident}|your incident}. The file is what happened." She takes her glasses down out of her hair and puts them on. "What do you still think about?"
* ["What I saw."]
    ~ eval_stays = "saw"
    ~ add_tag("Remembers what she saw")
    -> EVAL_125
* ["That I couldn't tell anyone."]
    ~ eval_stays = "silence"
    ~ add_tag("Remembers the silence")
    -> EVAL_125
* ["That it isn't finished."]
    ~ eval_stays = "unfinished"
    ~ add_tag("Thinks it will happen again")
    -> EVAL_125

// Reaction — what stays
=== EVAL_125 ===
# id: EVAL_125
# mode: day
~ set_header("Fourth floor, O'Connor Street", "Thursday morning")
{
- eval_stays == "saw":
    "Most people say that." She doesn't write it down. "The ones who worry me are the ones who tell me nothing stayed."
- eval_stays == "silence":
    She nods and writes. "Two years of training helps with what you saw. There's no course for the other thing."
- else:
    Her pen stops. "It isn't," she says. "Finished. You're allowed to know that — you work here."
}
* [Continue] -> EVAL_130

// SQ3 — anyone close
=== EVAL_130 ===
# id: EVAL_130
# mode: day
~ set_header("Fourth floor, O'Connor Street", "Thursday morning")
"Deep cover. Months, maybe longer. No calls home on a Branch line, no visits."
She lets the pen rest.
"Is there anyone outside the Branch who's close to you? Someone who notices when you don't call."
* ["Yes. A few people."]
    ~ eval_close = "yes"
    ~ add_tag("Has someone who would miss her")
    -> EVAL_135
* ["Not really. The job took that over a while ago."]
    ~ eval_close = "no"
    ~ add_tag("No close attachments")
    -> EVAL_135
* ["No," you lie.]
    ~ eval_close = "lie"
    ~ add_tag("Has someone who would miss her")
    -> EVAL_135

// Reaction — anyone close
=== EVAL_135 ===
# id: EVAL_135
# mode: day
~ set_header("Fourth floor, O'Connor Street", "Thursday morning")
{
- eval_close == "yes":
    "Good. Keep them." She writes. "We'll build the cover a reason to be bad at the phone. People go quiet all the time. What they can't do is go strange."
- eval_close == "no":
    "That's more common in this building than anywhere I've worked." She writes. "It makes you easier to deploy. I didn't say better."
- else:
    "Mm." The pen writes longer than a no should take.
}
* [Continue] -> EVAL_140

// SQ4 — being watched
=== EVAL_140 ===
# id: EVAL_140
# mode: day
~ set_header("Fourth floor, O'Connor Street", "Thursday morning")
She turns to a fresh page. Her tone doesn't move an inch.
"The club is a sex venue. Members have sex where other members can watch, and your cover has to live there." She looks up. "Job aside. Does being watched do anything for you?"
* ["Yes."]
    ~ eval_watched = "yes"
    ~ add_tag("Likes being watched")
    ~ add_kink("exhibitionism")
    -> EVAL_145
* ["No. Not my thing."]
    ~ eval_watched = "no"
    ~ add_tag("Prefers privacy")
    -> EVAL_145
* ["No," you lie.]
    ~ eval_watched = "lie"
    ~ add_tag("Likes being watched")
    ~ add_kink("exhibitionism")
    -> EVAL_145

// Reaction — being watched
=== EVAL_145 ===
# id: EVAL_145
# mode: day
~ set_header("Fourth floor, O'Connor Street", "Thursday morning")
{
- eval_watched == "yes":
    "Then parts of this assignment will be easier than the briefing made them sound." No smile. She writes a single word.
- eval_watched == "no":
    "Then we'll talk about acting before you go. It's a skill like any other. The ones who can't fake comfort come home tired."
- else:
    "All right." She caps the pen, and uncaps it again.
}
* [Continue] -> EVAL_150

// SQ5 — who knows
=== EVAL_150 ===
# id: EVAL_150
# mode: day
~ set_header("Fourth floor, O'Connor Street", "Thursday morning")
"Your intake interview, two years ago. You told us you're attracted to women as well as men." She says it the way she said [i]clearance[/i]. "People lie on intake, and it costs us months. You didn't. Thank you."
She turns the wedding band once with her thumb.
"So that's not the question. The question is who else knows."
* ["It's not a secret. People know."]
    ~ eval_out = "open"
    ~ add_tag("Openly bi")
    -> EVAL_155
* ["The people close to me know. It doesn't come up otherwise."]
    ~ eval_out = "quiet"
    ~ add_tag("Quietly bi")
    -> EVAL_155
* ["Nobody outside this building."]
    ~ eval_out = "closed"
    ~ add_tag("Closeted outside the Branch")
    -> EVAL_155

// Reaction — who knows
=== EVAL_155 ===
# id: EVAL_155
# mode: day
~ set_header("Fourth floor, O'Connor Street", "Thursday morning")
{
- eval_out == "open":
    "That simplifies the cover." One line, written without looking down. "We won't have to teach you to look comfortable."
- eval_out == "quiet":
    "Workable." She writes. "In there, strangers will know a thing most of your life doesn't. Some people find that restful."
- else:
    "Then Toronto is about to be complicated in a way Ottawa never was." She writes two lines. "We factor it in. That's all this is for."
}
* [Continue] -> EVAL_160

// SQ6 — why
=== EVAL_160 ===
# id: EVAL_160
# mode: day
~ set_header("Fourth floor, O'Connor Street", "Thursday morning")
She closes the folder. The pen goes down on top of it, capped.
"Last one. It's not on any form."
Your coffee has gone cold in front of you. Outside, a bus works its way up O'Connor.
"Two years ago you had every reason to walk away, and you signed on instead. Why are you still here?"
* ["I need to understand what happened to me."]
    ~ eval_why = "understand"
    ~ add_tag("Here to understand")
    -> EVAL_165
* ["Because it's real, and somebody has to deal with it."]
    ~ eval_why = "protect"
    ~ add_tag("Here to protect")
    -> EVAL_165
* ["Nothing else felt real afterward."]
    ~ eval_why = "real"
    ~ add_tag("Here because nothing else is real")
    -> EVAL_165

// Reaction — why
=== EVAL_165 ===
# id: EVAL_165
# mode: day
~ set_header("Fourth floor, O'Connor Street", "Thursday morning")
{
- eval_why == "understand":
    "Then you'll be careful," she says. "People looking for answers usually are, right up until they find one." She stands and puts her hand out.
- eval_why == "protect":
    "Good answer. It wears well." She stands and puts her hand out. "The ones who run on duty last the longest out there. They also file the driest reports. Try not to."
- else:
    For the first time all morning she takes a second before answering. "That one I understand personally," she says, and stands, and puts her hand out.
}
* [You shake it.] -> EVAL_170

// Off the record
=== EVAL_170 ===
# id: EVAL_170
# mode: day
~ set_header("Fourth floor, O'Connor Street", "Thursday morning")
Her handshake is dry and quick.
"You'll do follow-ups by secure pouch — a form a month. You'll hate them. Fill them in anyway."
She hands you your coat.
"And whatever you told me in that chair, keep track of which parts were true. Under a cover, that's the entire job."
The corridor still smells of new carpet. The elevator takes a long time to come.
* [You take the stairs instead.] -> EVAL_200

// The street
=== EVAL_200 ===
# id: EVAL_200
# mode: day
~ set_header("O'Connor Street, Ottawa", "Thursday morning")
Outside, Ottawa is doing its ten-forty-five: lanyards, gym bags, a mail truck idling in a no-parking zone. You cross at the light with everyone else.
From the far sidewalk you clock the fourth-floor window you just left, the way Robert glances east and then west. It's catching.
Three more days of paperwork. Then the boxes, and the train.
* [Continue] -> EVAL_205

// Eleven boxes
=== EVAL_205 ===
# id: EVAL_205
# mode: day
~ advance_days(4, "morning")
~ set_header("Your apartment, Ottawa", "Monday morning")
Two years in Ottawa fits into eleven boxes, and the Branch is storing nine of them. What's left is two suitcases and a garment bag: clothes for a woman who's about to be someone else.
Your footsteps sound different in the empty rooms. The keys go on the kitchen counter — the rent is paid through March by a numbered company you'll never hear of again.
Next to the keys, the appointment card. Dr. D. Caron. You almost pocket it. It goes in the last box instead.
* [You call the taxi.] -> EVAL_210

// The morning train
=== EVAL_210 ===
# id: EVAL_210
# mode: day
~ set_header("Ottawa Station, Tremblay Road", "Monday morning")
The morning train to Toronto boards from the far platform. Ottawa's station is a big glass box from the sixties, and on a Monday it's mostly civil servants and students going back to school.
Window seat, facing forward. Across the aisle a man in a golf shirt is asleep before the doors close.
The train moves before you expect it to. The platform slides. Then the canal, the backs of government buildings, the suburbs thinning into fields.
There's nothing to read. The briefing is memorized and burned, and the woman you're about to become doesn't exist on paper yet.
Toronto by mid-afternoon.
* [Continue] -> INTRO_800

