// GENERATED by twine-mcp-server `npm run export-ink` from sizzle/src/content/manitoulin.twee.
// Phase 1 bulk conversion — conventions: sizzle/docs/godot/INK-CONVENTIONS.md.
// Hand-edits must be recorded in sizzle/docs/godot/PHASE-1-CONVERSION-REPORT.md.

INCLUDE mirror.ink
INCLUDE ops.ink

// Story-local narrative state (not mirrored; ink may assign freely).
VAR man_sunroom_failed = false
VAR man_focal_held = false
VAR man_focal_failed = false
VAR man_structure_reasoned = false
VAR man_influence_granted = false
VAR man_skill_granted = false

-> MAN_085

// The long drive up
=== MAN_085 ===
# id: MAN_085
# avatar: man_day
# mode: day
~ set_date(2003, 8, 16, "afternoon")
~ set_header("THE HIGHWAY", "Saturday afternoon")
The two-lane unspools through granite cuts and black spruce, the heat shimmering off the asphalt ahead. You need this vacation.
{
- background == "RCMP constable":
    A year grinding through a junior posting out of the [url=gloss:Sault]Sault[/url], and this is the first real break you've taken since you started.
- background == "CSIS analyst":
    A year grinding at a junior analyst's desk in Ottawa, and this is the first real break you've taken since you started.
- background == "grad student":
    A year buried in your master's thesis at York, and your supervisor finally told you to disappear for a week before you came apart. Your mom's cousin's uncle owns a cottage out here, and through the vagaries of extended family you've got it to yourself, which is just as well: the rental car has already eaten most of your vacation budget.
- else:
    A year out of school with no job and too much time. Your mom's cousin's uncle owns a cottage out here, though, and through the vagaries of extended family you've got it to yourself for the week, which is just as well: the rental car has already eaten most of your budget.
}
Hopefully you can find the place before dark.
* [The road keeps going toward the island.] -> MAN_090

// Onto the island
=== MAN_090 ===
# id: MAN_090
# avatar: man_day
# mode: day
~ set_header("MANITOULIN APPROACH", "Saturday afternoon")
The swing bridge at Little Current is a single lane of old green steel. You wait while it pivots shut behind a sailboat, then bump across onto the island proper.
{ background == "RCMP constable":
    You've crossed it before, up this way on the job. It still feels like driving onto the edge of the map.
- else:
    WELCOME TO MANITOULIN, says the sign, WORLD'S LARGEST FRESHWATER ISLAND. You've never been this far up the province.
}
The town thins out fast. Bush and rock and the lake flashing blue through the trees, a gas bar with a hand-lettered sign for nightcrawlers. An ordinary north-country Saturday.
* [The island opens up ahead of you.] -> MAN_095

// A stop on the rock
=== MAN_095 ===
# id: MAN_095
# avatar: man_day
# mode: day
~ set_header("MANITOULIN ISLAND", "Saturday afternoon")
The general store has two gas pumps, a chest freezer of bait, and a pot of coffee that's been on the burner since morning. You fill the tank and buy the coffee anyway.
Heat comes off the granite lot in slow waves. A kid on the step works at a freezie and watches you like you're the most interesting thing to happen all day. Maybe you are.
{ background == "RCMP constable":
    You ask the woman at the till about the road out to the lake. "Quiet, mostly," she says. "Except the new crowd. City money." She says it the way you'd note a smell.
- else:
    You ask the woman at the till for the lake road. She points with her whole hand and tells you to watch for deer at dusk.
}
Back into the heat. Tank full, the light going long and gold.
* [You get back on the road.] -> MAN_100

// The island road
=== MAN_100 ===
# id: MAN_100
# avatar: man_day
# mode: day
~ set_time("evening")
~ set_header("MANITOULIN BACK ROAD", "Saturday evening")
Pavement gives out to gravel, and gravel gives out to two ruts with a crown of grass down the middle. Cottage roads. You crawl along watching for your turnoff, the lake somewhere off to your left behind a wall of cedar.
The day's heat is lifting off the rock now, the first cool breath of evening coming up out of the bush. Mosquitoes find the open window. You roll it up.
The place you're after is down here somewhere, small and quiet and yours for the week.
* [You follow the road toward the water.] -> MAN_105

// Dead in the water
=== MAN_105 ===
# id: MAN_105
# avatar: man_night
# mode: night
~ set_header("MANITOULIN BACK ROAD", "Saturday evening")
As the road winds deeper into the forest the sun drops below the trees and leaves the world in blue dusk. The lakeshore still shows through the trunks to your left, the last of the light going off it.
Then a loud POP, and the pedal under your foot sinks to the floor. You stand on the brakes, which thankfully still work, and coast onto the shoulder as the dashboard lights flicker and die. The engine ticks. The bush goes quiet.
{ background == "RCMP constable":
    Fuck. You should have taken her in before the trip. This is what deferred maintenance gets you.
- else:
    Fuck. This is what you get for going with the budget rental place.
}
Off through the trees there are voices, and up toward the water a cottage with its lights blazing into the dark.
{ background == "RCMP constable" or background == "CSIS analyst":
    You should have listened to your boss and bought a [url=gloss:cell phone]cell phone[/url].
- else:
    You should have listened to your friend Genevieve and bought a [url=gloss:cell phone]cell phone[/url]. But the damn things cost a fortune.
}
* [The house has lights and probably a phone.] -> MAN_110

// Nobody answers
=== MAN_110 ===
# id: MAN_110
# avatar: man_night
# mode: night
~ set_header("LAKEHOUSE DRIVE", "Saturday evening")
// [image] media/locations/lake-mansion.png — native presentation TBD
As you make your way toward the cottage on the lake you're struck by how HUGE it is. Cottage is the wrong word for this palatial new-money mansion. Three stories, with a fully kitted-out boathouse down past the lawn.
"Hello? My car broke down, could I use a phone?" you yell from the path up to the front door. There are people moving behind the drapes. Lots of them.
"FUCK MY ASS RAW! FUCK IT RAW!!!" a voice screams out from inside.
Well. Okay then. But you need that fucking phone.
* [You keep going up the drive.] -> MAN_115

// The front door
=== MAN_115 ===
# id: MAN_115
# avatar: man_night
# mode: night
~ set_header("LAKEHOUSE FRONT DOOR", "Saturday evening")
You knock and wait a full minute before knocking again. You can see people behind those curtains. A lot of people. They [i]must[/i] have heard you.
You knock a third time, louder, harder. The door pops open. It wasn't locked, or even properly shut.
Inside is a foyer full of coats and kicked-off sandals and shoes, enough for several dozen people. Shadows move in the hallway ahead of you, and from a room to your right come wet, rhythmic sounds.
{
- background == "RCMP constable":
    You count without meaning to. Exits, doors, how many pairs of shoes. The job doesn't switch off because you're on holiday.
- background == "CSIS analyst":
    Thirty pairs of shoes by the door and not one person answering it. The arithmetic of that sits wrong.
- background == "grad student":
    Thirty pairs of shoes and nobody coming to the door. Every model of crowd behaviour you know says someone should have.
- else:
    Thirty pairs of shoes, and not one person willing to cross a room to a knocking door. You've been to enough parties, even the "good" ones, to know that's off.
}
* [You step inside.] -> MAN_120

// The great room
=== MAN_120 ===
# id: MAN_120
# avatar: man_night
# mode: night
~ set_header("LAKEHOUSE GREAT ROOM", "Saturday evening")
You were pretty sure there were people fucking in here, but the [i]scale[/i] of it is impressive.
Stepping into the sprawling great room, warm air thick with cedar and sweat and cum hits your nose. At least twenty bodies writhe across plush rugs and leather couches by the massive stone fireplace.
A woman on all fours takes two men at once while fingering another woman. Nearby, a man is bound and edged relentlessly as a circle of guests watches and strokes.
On one side you can see the curtains that blocked your view before. On the other floor-to-ceiling windows highlight the moonlit lake.
"Hello? Anyone?"
They ignore you.
* [You make someone look at you.] -> MAN_125

// Look at me — # check protocol knot
=== MAN_125 ===
# id: MAN_125
# avatar: man_night
# mode: night
# check: composure 2d6 7
~ set_header("LAKEHOUSE GREAT ROOM", "Saturday evening")
You tiptoe around the tangle of limbs toward a muscular man fiercely railing a moaning woman from behind, her breasts swinging with each deep thrust.
“Hey! Excuse me!” you call out, voice rising.
He doesn’t even glance your way. Frustrated, you slap him hard across the face. Nothing. He just grunts and keeps pounding into her harder, completely lost in the rhythm.
{ check_passed:
    You step back and make yourself watch it cold. That is deeply fucking weird. You hit him hard enough to hurt and got nothing, not a flinch. The whole room is locked into the same thing, wherever they've all gone. Some distant part of you notes that you aren't panicking, and hopes that's a good sign.
    * [You keep looking around.] -> MAN_130
- else:
    Heart hammering, you stumble back, face burning. This isn’t right. No one even flinched. A cold shiver runs down your spine—what the hell is this place?
    * [You force yourself to keep looking around.] -> MAN_130
}

// Party favours
=== MAN_130 ===
# id: MAN_130
# avatar: man_night
# mode: night
~ set_header("LAKEHOUSE GREAT ROOM", "Saturday evening")
On your way through, the details start adding up wrong. A folding catering table with a sterno tray gone cold. Plastic champagne flutes. A glitter banner that reads FORBIDDEN ISLAND.
Taped to the wall by the fireplace is a printout: a diagram, five lines meeting in a star, the kind of thing you'd pull off a website at two in the morning. Someone's chalked the same shape onto the floorboards, half scuffed away now under all the moving feet. Dollar-store tealights ring it.
A party trick. Somebody printed off a diagram and lit some candles for a laugh, the way you'd run a séance at a sleepover.
Nobody's laughing now.
* [You move deeper into the house.] -> MAN_135

// The kitchen
=== MAN_135 ===
# id: MAN_135
# avatar: man_night
# mode: night
~ set_header("LAKEHOUSE KITCHEN", "Saturday evening")
You slip past the great room and into the kitchen.
The air is heavier here, thick with the smell of sweat, spilled wine, and sex. Two women are bent over the granite island while a man takes one from behind and fingers the other; another couple fucks slowly against the fridge, her leg hooked high around his hip. Their faces are slack, eyes half-lidded.
Heat blooms low in your belly, uninvited. Your nipples tighten against your shirt. For one disorienting second it almost makes sense.
You catch yourself breathing faster. [i]What the fuck is wrong with me?[/i]
* [You reach the back hall.] -> MAN_140

// Forward or back
=== MAN_140 ===
# id: MAN_140
# avatar: man_night
# mode: night
~ set_header("LAKEHOUSE BACK HALL", "Saturday evening")
The pull is stronger now, a low insistent tug behind your sternum. Ahead, through the French doors, you can see the lawn sloping down toward the dark water. Behind you, the front entrance and the promise of escape.
You hesitate, heart hammering.
* [You push toward the water.] -> MAN_145
* [You try to leave.]
    You turn sharply, aiming for the front door and the cool night air beyond it. Your feet carry you back through the great room, past the indifferent bodies, but something catches in your mind. Something is wrong here. Something you need to fix.
    * * [You turn back toward the water.] -> MAN_145

// The sunroom — # check protocol knot
=== MAN_145 ===
# id: MAN_145
# avatar: man_night
# mode: night
# check: composure 2d6 8
~ set_header("LAKEHOUSE SUNROOM", "Saturday evening")
You step through the French doors into the sunroom.
Half a dozen guests are tangled together across the floor and low couches. A woman on all fours moans into a man’s cock. Beside them, a man lies on his back as two women ride him—one on his face, the other sinking down onto his shaft in slow, rolling movements. A third woman kneels between another couple, licking and sucking wherever her mouth can reach. Blank, dreamy expressions. No one looks at you.
Heat floods your body. Your clit throbs in time with their rhythm. God, it looks good. Why not just walk over, drop to your knees, let them use you too? It would feel so right…
Your thighs press together involuntarily. The thought feels dangerously reasonable.
{ check_passed:
    The images keep pulling at you: the slick sounds, the rolling hips, the shameless tangle of bodies. But you force your eyes away and keep moving. Your legs feel heavy, reluctant, but they obey.
    No doubt it looks fun. But something here is [i]clearly[/i] wrong.
    You slip past the sunroom and push through the back doors into the cool night air, heart pounding.
    * [You get through the sunroom doors.] -> MAN_150
- else:
    ~ man_sunroom_failed = true
    You take an involuntary half-step forward, one hand already reaching toward the nearest body, the other slipping into your shorts. Heat surges through you, thick and liquid. For a dizzying moment it feels right to walk over, to kneel, to let yourself be pulled into the warm, mindless rhythm with them.
    You yank your hand out of your panties. They're wet. Shame and arousal twist together in your gut as you force yourself onward, legs unsteady.
    * [You pull yourself through the sunroom doors.] -> MAN_150
}

// Out the back
=== MAN_150 ===
# id: MAN_150
# avatar: man_night
# mode: night
~ set_time("night")
~ set_header("LAKEHOUSE BACK LAWN", "Saturday night")
You push through the back doors and the night air hits in a shock, cool and sharp, laced with pine and lake water.
The lawn slopes gently down toward the North Channel, black and star-pricked, no city glow anywhere. Torchlight flickers along the dock at the bottom, casting long, wavering shadows across the grass.
The pull in your chest is stronger out here, almost physical now. Down at the end of the dock you can see the densest knot of bodies, moving together in the firelight.
Your pulse throbs between your legs.
* [You go down toward the dock.] -> MAN_155

// The dock
=== MAN_155 ===
# id: MAN_155
# avatar: man_night
# mode: night
~ set_header("PRIVATE DOCK", "Saturday night")
The dock boards creak under your feet. At the far end, a five-point chalk marking glows faintly in the dark, a cold light the candles can't account for. Photoluminescent, you tell yourself. The glow-in-the-dark kind kids buy. You don't quite believe it. Around it, the frenzy is thickest.
A half-dozen bodies move in a slow, heaving knot. A woman straddles one man reverse-cowgirl, riding his cock with wet, rhythmic slaps. Beside them, two men jerk off with their eyes closed. A woman lies spread beneath another man, legs locked around his waist as he thrusts into her. Blank, blissful faces. Slick skin. The air is heavy with the sounds and smells of sex.
It looks so god. damn. inviting.
Your pussy aches. Your mind tilts dangerously toward surrender.
* [You reach the centre of it.] -> MAN_160

// Almost — # check protocol knot
=== MAN_160 ===
# id: MAN_160
# avatar: man_night
# mode: night
# check: composure 2d6 9
~ set_header("PRIVATE DOCK", "Saturday night")
At the centre of everything is the marking: five lines of chalk meeting in a rough star, half-smudged already by bare heels and spilled wax. Cheap tealights gutter in a loose ring around it. The air smells of citronella and sweat and something thicker.
{ check_passed:
    ~ man_focal_held = true
    You plant your feet on the warm dock boards and [i]refuse[/i].
    The pull is still there—thick, sweet, perfectly reasonable in your own head. But you grip the railing hard enough that the wood bites your palms. The tableau around the marking keeps moving: slick skin, rolling hips, low moans rising into the night air.
    It would be so easy to step in.
    But you don’t.
    Your eyes stay fixed on the chalk lines at the centre of it all.
    * [You look for the thing holding it together.] -> MAN_165
- else:
    ~ man_focal_failed = true
    The pull wins for a moment. Your knees buckle. You sink down, one hand reaching toward the nearest body: a woman on her back, legs spread, taking a thick cock. You thumb her nipple. She doesn't look at you.
    A candle tips, hot wax spilling across your knuckles. The contact jolts through you. The compulsion is suddenly visible.
    You yank your hand back, gasping.
    * [Your hand finds the marking under you.] -> MAN_165
}

// The pattern is the thing — # check protocol knot
=== MAN_165 ===
# id: MAN_165
# avatar: man_night
# mode: night
# check: academic/streetwise 2d6 7
~ set_header("PRIVATE DOCK", "Saturday night")
You’re still on your knees at the edge of the marking, heart hammering, skin flushed and oversensitive, but your mind is fighting for traction again.
{ check_passed:
    ~ man_structure_reasoned = true
    The chalk lines. The candles. Everything in the room — the bodies, the moans, the need — radiating out from this stupid little diagram like it’s the centre of the universe. It started as a party trick. Dollar-store crap. A dare. And somehow it worked. You stare at the five-pointed smear under your hand. Break the pattern, break the hold.
    * [You ruin the pattern.] -> MAN_170
- else:
    No epiphany. Just a raw, animal surge: [i]this thing is doing this to me, to all of them—get rid of it.[/i] You don’t need to understand how. You just need it gone.
    * [You wreck what is under your hands.] -> MAN_170
}

// Break the circle
=== MAN_170 ===
# id: MAN_170
# avatar: man_night
# mode: night
~ set_header("PRIVATE DOCK", "Saturday night")
Your hand is flat on the chalk. The lines are just lines, powder and grit, already smearing where you've leaned into them.
It would take so little. A scuff, a kick, anything that turns the shape into not-a-shape.
The heat is still in you, the pull, the part that wants to lie down in the middle of it and stop fighting. You use the other part. The one that decides things.
* [You drag your foot through the chalk.] -> MAN_175
* [You kick the candles apart.] -> MAN_175
* [You haul a chair across the marking.] -> MAN_175
* [You pour melted ice over the diagram.] -> MAN_175

// Cut wire
=== MAN_175 ===
# id: MAN_175
# avatar: man_night
# mode: night
~ set_header("PRIVATE DOCK", "Saturday night")
{ not man_influence_granted:
    ~ temp man_influence = 2
    { man_sunroom_failed or man_focal_failed:
        ~ man_influence = 3
    }
    ~ adjust_influence(man_influence)
    ~ man_influence_granted = true
}
{ not man_skill_granted:
    {
    - man_focal_held:
        ~ grant_skill("composure", 1)
    - man_structure_reasoned:
        ~ grant_skill("academic", 1)
    - else:
        ~ grant_skill("confrontation", 1)
    }
    ~ man_skill_granted = true
}
The shape comes apart and the whole world lurches.
For one second the music is suddenly enormous, some bright stupid pop song that's been playing this entire time and that you never once heard. Then it cuts out mid-chorus, like a plug pulled from a wall.
And the room lets go.
You feel it leave you first. The heat, the pull, the lovely reasonable wanting, gone between one breath and the next. Around you the sounds change. A moan falters. Someone says "what" in a small, lost voice. All around you, hands go still on skin.
* [The party surfaces around you.] -> MAN_180

// Surfacing
=== MAN_180 ===
# id: MAN_180
# avatar: man_night
# mode: night
~ set_header("PRIVATE DOCK", "Saturday night")
They come up like divers, all at once and too fast.
A man sits back on his heels, blinking, and you watch him notice his own nakedness, then the stranger beneath him, then the dark all around. His mouth opens and nothing comes out.
It happens everywhere at once. People peeling apart, reaching for clothes that aren't near them, saying names that turn out to be the wrong names. A woman with her reading glasses still on and nothing else. A wedding ring on a hand that is holding the wrong hand.
Nobody looks at you. For a different reason now. They can't look at anyone.
* [Someone has to make the call.] -> MAN_185

// Someone has to call this in
=== MAN_185 ===
# id: MAN_185
# avatar: man_night
# mode: night
~ set_header("LAKEHOUSE", "Saturday night")
There's a [url=gloss:cordless phone]cordless phone[/url] in the kitchen, on the counter by the cold catering trays. You stand holding it while the dial tone hums.
{ background == "RCMP constable":
    You identify yourself to the operator, give the road, ask for an ambulance and the [url=gloss:OPP]OPP[/url]. Then you start doing the thing the job trained you for: building it into a report, in your head, while you wait. Twenty-odd adults. No injuries you can see. No crime you can name. Cause of incident, you'd have to leave blank. You'll be leaving it blank for a long time.
- else:
    You tell the operator there's been an emergency, people hurt, you don't know how to say it. You give the road. When she asks what happened you open your mouth and there's nothing in it but the dial tone of your own head. None of this is going to hold together. You know that already.
}
* [There's nothing more you can do here.] -> MAN_190

// The drive back
=== MAN_190 ===
# id: MAN_190
# avatar: man_night
# mode: night
~ set_header("MANITOULIN ISLAND", "Saturday night")
You give your statement twice, to two different officers, and neither time does it come out sounding like anything that could have happened. Eventually someone puts you in the back of a cruiser to run you back to town. Your dead car can wait for daylight and a tow.
Out the window the bush goes by black and endless. The thing that keeps coming back isn't the bodies or the chalk or the crying. It's how close you came. How reasonable it felt. How a person can step into something like that and never once decide to.
I just wanted to use the fucking phone.
You'll think that a lot, after. It stops being funny early.
* [A week later, the file has a number.] -> MAN_200

// Occurrence report — Branch file extract STUB (native scene template later)
=== MAN_200 ===
# id: MAN_200
# screen: menu
# scene: branch_file_extract
# extract: man_occurrence_report_03_MAN_0816
~ set_date(2003, 8, 23, "morning")
~ set_header("BRANCH FILE EXTRACT", "Saturday morning")
Incident File 03-MAN-0816, extract. Rendered by the native BranchFileExtract scene template; this knot is a placeholder.
* [You turn the page.] -> MAN_205

// Recommendation — Branch file extract STUB (native scene template later)
=== MAN_205 ===
# id: MAN_205
# screen: menu
# scene: branch_file_extract
# extract: man_recommendation_r_flett
~ set_header("BRANCH FILE EXTRACT", "Saturday morning")
Recruitment Recommendation, R. Flett, 2003.08.23. Rendered by the native BranchFileExtract scene template; this knot is a placeholder.
* [The file closes.]
    // TODO(runtime): native CC-500 handoff sets inciting_incident to "the Dark of Manitoulin"
    ~ set_date(2005, 9, 12, "morning")
    -> man_end

// Native-scene handoff — original twee target(s): CC-500 Summary.
=== man_end ===
# id: man_end
The manitoulin sequence ends here; the runtime hands off to the native scene (CC-500 Summary).
-> END

