// GENERATED by twine-mcp-server `npm run export-ink` from sizzle/src/content/pale.twee.
// Phase 1 bulk conversion — conventions: sizzle/docs/godot/INK-CONVENTIONS.md.
// Hand-edits must be recorded in sizzle/docs/godot/PHASE-1-CONVERSION-REPORT.md.

INCLUDE mirror.ink
INCLUDE ops.ink

// Story-local narrative state (not mirrored; ink may assign freely).
VAR pale_rule_read = false
VAR pale_unseen = false
VAR pale_gaze_grazed = false
VAR pale_loophole_reasoned = false
VAR pale_command_held = false
VAR pale_command_bitten = false
VAR pale_influence_granted = false
VAR pale_skill_granted = false

-> PALE_085

// A reason to be in Ottawa
=== PALE_085 ===
# id: PALE_085
# avatar: pale_night
# mode: night
~ set_date(2003, 8, 18, "evening")
~ set_header("DOWNTOWN OTTAWA", "Monday evening")
Ottawa goes home at five and takes the sidewalks with it. By evening the government blocks are quiet enough to hear your own footsteps, and the day's heat is still coming up off the stone. Over the river, the sky has spent the last hour stacking up something green-black and serious.
{
- background == "RCMP constable":
    Three days of a policing conference at the Château Laurier, and tonight you finally got out for a dinner that wasn't banquet chicken. Worth it. The hotel's a few blocks back, and you're full and slow and in no hurry.
- background == "CSIS analyst":
    An all-day interdepartmental session in one of the Château Laurier's meeting rooms: slide carousels, weak coffee, a binder you signed for and will sign back in tomorrow. You stayed at the reception exactly as long as politeness required. Home is a twenty-minute walk, most of it pretty.
- background == "grad student":
    You promised yourself one real trip before the thesis ate the rest of the summer, and Ottawa in August is keeping its end: the gallery this morning, the canal this afternoon, a hotel room nicer than you can strictly justify. You've decided not to think about the Visa bill until September.
- else:
    You booked this trip in March, back when you had a job. The room at the Château Laurier was non-refundable. So here you are: unemployed, on vacation out of spite, walking back to the nicest hotel you'll ever sleep in.
}
The first drops come down fat enough to feel personal.
* [The weather breaks before you reach shelter.] -> PALE_090

// The sky opens up
=== PALE_090 ===
# id: PALE_090
# avatar: pale_night
# mode: night
~ set_header("DOWNTOWN OTTAWA", "Monday evening")
The sky doesn't bother with a warning. One fat drop, two, and then the whole thing comes down at once, a white roar of water that turns Rideau Street into a riverbed.
Half a block ahead an umbrella goes inside out, and its owner gives up on it without breaking stride. Awnings fill. An [url=gloss:OC Transpo]OC Transpo[/url] bus sighs past, windows fogged solid.
You run, one arm up over your head like that's ever helped anyone, the rain finding the back of your collar anyway.
* [The nearest dry doorway is the hotel's.] -> PALE_095

// Into the lobby
=== PALE_095 ===
# id: PALE_095
# avatar: pale_night
# mode: night
~ set_header("OTTAWA HOTEL LOBBY", "Monday evening")
The doorman has given up sorting arrivals into anything orderly. You come through in a knot of strangers, everyone dripping, everyone laughing the way people laugh when the weather has made fools of the whole street at once.
Inside is brass and warm light and the smell of wet wool. A check-in line three deep. A bellhop towelling down a luggage cart. Somewhere behind the columns a piano keeps at it, mostly drowned out. The rain is a long held note against the glass, and the crowded lobby hums along underneath it, ordinary as a Monday.
* [You cross out of the rain.] -> PALE_100

// Out of the rain
=== PALE_100 ===
# id: PALE_100
# avatar: pale_night
# mode: night
~ set_header("OTTAWA HOTEL LOBBY", "Monday evening")
The storm has settled in to stay. Half the lobby is waiting it out with you: wet couples by the windows, a man arguing gently with the concierge about a taxi that isn't coming.
{background == "CSIS analyst": Home is twenty minutes of open sky away. Not in this.|Your room is upstairs, but the evening doesn't feel finished, and your shoes are already ruined.} A drink, then. The lounge is off the back of the lobby, past the elevators, and a wingback chair beats standing here dripping on the marble.
Crossing toward it, somewhere between the front desk and the elevators, the lobby's hum goes uneven on you. Nothing you could point to. Yet.
* [You notice the corner where the noise drops.] -> PALE_105

// The quiet corner
=== PALE_105 ===
# id: PALE_105
# avatar: pale_night
# mode: night
~ set_header("OTTAWA HOTEL LOBBY", "Monday evening")
The lounge opens off the back of the lobby through a wide arch, and you're three steps from it when you place what's bothering you. Sound. There isn't any.
The lobby behind you is all storm-talk and luggage wheels and the piano. Past the arch: nothing. No conversation, no glasses, no newspaper. Lounges are never silent. Even empty ones have a clock.
Through the arch you can make out armchairs, unlit lamps, curtains drawn to the floor. Hard to say if anyone's in there at all.
* [You look from cover.] -> PALE_110

// Too orderly
=== PALE_110 ===
# id: PALE_110
# avatar: pale_night
# mode: night
~ set_header("HOTEL LOUNGE ALCOVE", "Monday evening")
This quiet corner behind the lobby is strange. There should be more people here.
The room is banked with tall windows, every one curtained to the floor, what's left of the evening only getting in at the edges. The rain against the glass makes a wall of soft noise.
As far as you can tell, the only person in the dark room is a woman seated by the grand fireplace at the back.
* [Move toward the woman.] -> PALE_115

// Pale eyes
=== PALE_115 ===
# id: PALE_115
# avatar: pale_night
# mode: night
~ set_header("HOTEL LOUNGE ALCOVE", "Monday evening")
As you move toward the woman, something deep in your gut feels wrong. You know you can't look at her. And she can. not. know. you're. there.
You glance at her from the corner of your eye. She has arranged herself on a high-backed chair near the fireplace. Her feet are up on something. You realize that there are more people around her.
* [You watch what she does.] -> PALE_120

// The rule — # check protocol knot
=== PALE_120 ===
# id: PALE_120
# avatar: pale_night
# mode: night
# check: agent/academic 2d6 7
~ set_header("HOTEL LOUNGE ALCOVE", "Monday evening")
She's about to speak to someone beside her chair. First she crooks one finger and waits, and waits, until the person's face comes up to hers.
"Crawl out of the room and get me another coffee."
A woman in a hotel uniform drops to her hands and knees and goes, fast, like it's a race, through a service door on the far wall. A swing of kitchen light, a clatter of dishes, gone. Her expression, in the half-second you had it, was nothing at all.
{ check_passed:
    ~ pale_rule_read = true
    She waited. That's what you saw: she didn't speak until the staffer looked at her. The order rode the look. It's the eyes.
    * [You adjust your angle before her eyes catch you.] -> PALE_125
- else:
    However she's doing it, you didn't catch it. A word, and a grown woman went to the floor like it was her own idea. You're missing the part that matters.
    * [You adjust your angle.] -> PALE_125
}

// The mirror
=== PALE_125 ===
# id: PALE_125
# avatar: pale_night
# mode: night
~ set_header("OTTAWA HOTEL LOBBY", "Monday evening")
What you have is slivers: a shoulder, the woman's hand, her feet up on something that breathes. You need the whole room, and you need it without walking into it.
There's a mirror. Gilt-framed, tall as a door, hung over the sideboard on the lobby side of the arch, and angled to hold most of the alcove in one piece.
Something in you is certain the glass cuts both ways. If you can see her eyes in it, her eyes can see yours.
* [You use the mirror.]
    You ease along the sideboard and let the glass do the looking.
    It's all there at once, small and complete: the chair, the people arranged around it, the stillness. Then her head turns a degree, and your stomach drops, and the pale eyes pass across the mirror without catching, a lighthouse sweeping past a boat it doesn't know about.
    * * [The arrangement comes into focus.] -> PALE_130
* [You stay with cover and glimpses.]
    You stay in the seam between curtain and arch and build the room a glimpse at a time: a bare shoulder, a kneeling back, the woman's hand rising and falling at her mouth. Slow work. Each look costs seconds, and buys you inches.
    * * [The arrangement comes into focus piece by piece.] -> PALE_130

// The arrangement
=== PALE_130 ===
# id: PALE_130
# avatar: pale_night
# mode: night
~ set_header("HOTEL LOUNGE ALCOVE", "Monday evening")
The footrest is a man. Naked, on all fours, her stockinged heels crossed on the small of his back. His glasses are still on. He's hard, flushed dark, and no part of him moves.
Beside the chair a younger woman kneels with a dish of cut melon, naked except for a conference lanyard, lifting a piece to the woman's mouth, waiting, lifting the next. Her nipples are stiff, and her thighs, where she kneels, are wet.
On the other side a man stands at attention in half a suit, trousers pooled at his ankles, cock rigid, her closed umbrella hooked over it, still dripping rain onto the carpet.
Behind the chair, a man and a woman stopped mid-fuck over the arm of a sofa, him buried in her to the root, both faces slack, eyes on nothing.
No ropes. No one holding anyone down. Just a seated woman, and people arranged around her like furniture that breathes.
You still haven't looked at her face.
* [You make yourself not look up.] -> PALE_135

// Don't look up — # check protocol knot
=== PALE_135 ===
# id: PALE_135
# avatar: pale_night
# mode: night
# check: composure/agent 2d6 8
~ set_header("HOTEL LOUNGE ALCOVE", "Monday evening")
The woman's head begins to turn. Not at a sound. Not at you. A slow sweep of the room, the way a searchlight doesn't need a reason.
Your eyes want to come up and meet it. That's the part that scares you: being looked at pulls, and something in you wants to answer.
{ check_passed:
    ~ pale_unseen = true
    You put your eyes on the carpet, flatten into the curtain's shadow, and count. Four. Five. When you risk the angle again, her face is turned away and her hand is out for the next piece of fruit.
    * [You stay low and think.] -> PALE_140
- else:
    ~ pale_gaze_grazed = true
    You're half a beat slow. The sweep crosses the space where you are and something snags, the way a nail catches a sleeve. Not a lock. The edge of it only. But for that half-second your whole body leans toward being seen, and you have to drag yourself back behind the curtain.
    * [You duck out of it and think.] -> PALE_140
}

// She can't just walk out
=== PALE_140 ===
# id: PALE_140
# avatar: pale_night
# mode: night
~ set_header("OTTAWA HOTEL LOBBY", "Monday evening")
Out, then. The thought arrives sounding like a plan: back through the arch, across the lobby, gone, and let tomorrow decide what tonight was.
Except the arch is in her line, and the lobby is forty feet of bright, open marble.
And there are the people. The glasses. The lanyard. All evening the lobby has walked past that arch without noticing, and if it hasn't noticed by now, nobody is coming.
* [You try to slip away.]
    You make it two steps toward the arch before the math does itself: ten seconds in her line of sight, and a word travels faster than you do.
    You come back into the shadow. There's no version of leaving that doesn't pass through her eyes.
    * * [You look for the loophole instead.] -> PALE_145
* [You decide to stop it.] -> PALE_145

// The loophole — # check protocol knot
=== PALE_145 ===
# id: PALE_145
# avatar: pale_night
# mode: night
# check: academic/streetwise 2d6 7
~ set_header("OTTAWA HOTEL LOBBY", "Monday evening")
It has to end here, then, and none of the normal endings apply. You can't argue with her. You can't shout for help without volunteering whoever comes running. You can't even look at her long enough to aim.
One try. Blind. Think.
{ check_passed:
    ~ pale_loophole_reasoned = true
    The staffer. The woman waited for her eyes before she spoke, and even then there was a gap, half a breath between the word and the body obeying. So the command needs two things: her eyes on you, and a moment to take hold.
    A swing that's already falling gives her neither. Start it from behind her chair, where she can't see you. By the time she can, it has to be too late to stop. Too late for her, and too late for you.
    * [You need something heavy.] -> PALE_150
- else:
    You never do work it out, not in words, not in anything you could explain afterward. Your body skips to the end: it wants something heavy in your hands, and it wants you behind that chair, where she can't see you. The plan arrives whole, from somewhere below thinking, and you go with it.
    * [You need something heavy.] -> PALE_150
}

// Something heavy
=== PALE_150 ===
# id: PALE_150
# avatar: pale_night
# mode: night
~ set_header("OTTAWA HOTEL LOBBY", "Monday evening")
The lounge and the lobby between them offer a short inventory.
A fire extinguisher in its bracket beside the service door, red and fat and heavier than it looks. A side chair by the writing desk, oak, liftable. The bellhop's luggage cart, abandoned mid-lobby with someone's garment bag still on it. A brass stanchion by the arch, top-heavy as a sledgehammer.
And one blind lane: along the curtains, behind the wing of her chair, where the high back will hold her eyes off you until you're inside arm's reach.
* [You take the fire extinguisher.] -> PALE_155
* [You take a lobby chair.] -> PALE_155
* [You use the luggage cart.] -> PALE_155
* [You take the brass stanchion.] -> PALE_155

// The point of no return
=== PALE_155 ===
# id: PALE_155
# avatar: pale_night
# mode: night
~ set_header("HOTEL LOUNGE ALCOVE", "Monday evening")
You pick a point on the back of her chair, shoulder height, and you don't look anywhere else.
The lane along the curtains is six steps. You take them slow, weight settling before each one, the weight in your hands the only thing in the world. The rain keeps its noise up. Under it, close now, the small wet sound of chewing on the other side of the wingback.
Last step. You set your feet the way you'd set them on ice.
Both arms. Up.
You are already swinging.
* [The woman looks up.] -> PALE_160

// "STOP." — # check protocol knot
=== PALE_160 ===
# id: PALE_160
# avatar: pale_night
# mode: night
# check: composure 2d6 9
~ set_header("HOTEL LOUNGE ALCOVE", "Monday evening")
Something gives you away. Air, shadow, the creak of your own grip; you'll never know what.
Her face comes around the wing of the chair. Her eyes find yours, pale as milk in water, and her mouth opens without any hurry at all.
"STOP."
{ check_passed:
    ~ pale_command_held = true
    The word lands somewhere your ears have nothing to do with, and it is true the way gravity is true: you must stop.
    But the swing stopped being yours half a second ago. There's nothing left in it for you to take back. Your arms aren't asking.
    * [Momentum carries through.] -> PALE_165
- else:
    ~ pale_command_bitten = true
    The word closes around you like a hand. And you stop. Everything that's still yours stops: breath, thought, grip.
    The swing isn't yours anymore. It finishes without you.
    For one impossible second, you are a thing that obeys, all the way down. You understand the footrest completely.
    * [Momentum carries through anyway.] -> PALE_165
}

// Impact
=== PALE_165 ===
# id: PALE_165
# avatar: pale_night
# mode: night
~ set_header("HOTEL LOUNGE ALCOVE", "Monday evening")
{ not pale_influence_granted:
    ~ temp pale_influence = 1
    { pale_gaze_grazed or pale_command_bitten:
        ~ pale_influence = 2
    }
    ~ adjust_influence(pale_influence)
    ~ pale_influence_granted = true
}
{ not pale_skill_granted:
    {
    - pale_unseen or pale_rule_read:
        ~ grant_skill("agent", 1)
    - pale_loophole_reasoned:
        ~ grant_skill("academic", 1)
    - pale_command_held:
        ~ grant_skill("composure", 1)
    - else:
        ~ grant_skill("confrontation", 1)
    }
    ~ pale_skill_granted = true
}
The sound is heavier than you expected, and quieter. One deep thud. The coffee cup rings against its saucer.
She goes sideways out of the chair and doesn't put her hands out. The carpet takes her with a sound like a dropped coat.
Quiet, then. Rain, your own blood in your ears, nothing else. You can't remember deciding to stop swinging.
* [The room comes back to itself.] -> PALE_170

// The room comes back
=== PALE_170 ===
# id: PALE_170
# avatar: pale_night
# mode: night
~ set_header("HOTEL LOUNGE ALCOVE", "Monday evening")
The umbrella hits the floor first.
Then the man it was hanging from gasps, one long ragged pull of air, and grabs for his waistband. The kneeling woman looks at the dish in her hands as if it has just appeared there, sets it down, and starts to shake. Behind the chair a woman's voice says "off, off, get off," and there's the fast, fumbling sound of two people coming apart.
The footrest man crawls two steps, stops, and folds down onto the carpet with his glasses still on, crying without any noise.
Nobody looks at the woman on the floor. Nobody looks at you.
* [The wrong people arrive too quickly.] -> PALE_175

// They were already coming
=== PALE_175 ===
# id: PALE_175
# avatar: pale_night
# mode: night
~ set_header("OTTAWA HOTEL LOBBY", "Monday evening")
They come through the lobby arch and the service door at the same time, six of them, in plain suits, with laminated cards that say something that isn't police. Nobody runs. Two go to the woman on the floor, one to each of the others, voices low and kind and completely unsurprised.
Nobody called them. There wasn't time; the lobby out there is still arguing about taxis. But they come in already knowing where the woman is and which doors need watching, and they get to you last, as if you've already been sorted.
A woman your mother's age asks you four quiet questions, all of them the right ones, and writes nothing down.
* [They tell you to go home.] -> PALE_180

// The way home
=== PALE_180 ===
# id: PALE_180
# avatar: pale_night
# mode: night
~ set_header("OTTAWA", "Monday night")
{ background == "CSIS analyst":
    The storm has worn itself out by the time you're halfway home, and the streets have that rinsed, emptied look. You walk the whole way without meeting a single pair of eyes, and you only notice you're doing it at your own front door.
- else:
    Your room is four floors up. You share the elevator with a couple still laughing about the rain, and you watch the brass doors the whole ride, and you don't know you're avoiding their eyes until they get out.
}
In bed, you keep arriving at the same half-second and stopping. Not the swing. Not the woman folding onto the carpet. The word. STOP, and everything in you agreeing.
For one second, another person's sentence was the truest thing in your body.
You leave the bathroom light on. You don't look at the mirror.
* [Days later, the file exists.] -> PALE_200

// Field report — Branch file extract STUB (native scene template later)
=== PALE_200 ===
# id: PALE_200
# screen: menu
# scene: branch_file_extract
# extract: pale_field_report_03_OTT_0818
~ set_date(2003, 8, 22, "morning")
~ set_header("BRANCH FILE EXTRACT", "Friday morning")
Incident File 03-OTT-0818, extract. Rendered by the native BranchFileExtract scene template; this knot is a placeholder.
* [You turn the page.] -> PALE_205

// Recommendation — Branch file extract STUB (native scene template later)
=== PALE_205 ===
# id: PALE_205
# screen: menu
# scene: branch_file_extract
# extract: pale_recommendation_r_flett
~ set_header("BRANCH FILE EXTRACT", "Friday morning")
Recruitment Recommendation, R. Flett, 2003.08.22. Rendered by the native BranchFileExtract scene template; this knot is a placeholder.
* [The file closes.]
    // TODO(runtime): native CC-500 handoff sets inciting_incident to "the Woman with the Pale Eyes"
    ~ set_date(2005, 9, 12, "morning")
    -> pale_end

// Native-scene handoff — original twee target(s): CC-500 Summary.
=== pale_end ===
# id: pale_end
The pale sequence ends here; the runtime hands off to the native scene (CC-500 Summary).
-> END

