// GENERATED by twine-mcp-server `npm run export-ink` from sizzle/src/content/wds.twee.
// Phase 1 bulk conversion — conventions: sizzle/docs/godot/INK-CONVENTIONS.md.
// Hand-edits must be recorded in sizzle/docs/godot/PHASE-1-CONVERSION-REPORT.md.

INCLUDE mirror.ink
INCLUDE ops.ink

// Story-local narrative state (not mirrored; ink may assign freely).
VAR wds_vector_reasoned = false
VAR wds_deep_failed = false
VAR wds_spine_held = false
VAR wds_spine_failed = false
VAR wds_influence_granted = false
VAR wds_skill_granted = false

-> WDS_085

// The last stretch of highway
=== WDS_085 ===
# id: WDS_085
# avatar: wds_night
# mode: night
~ set_date(2003, 8, 20, "evening")
~ set_header("ONTARIO HIGHWAY", "Wednesday evening")
The radio's been losing its station for twenty minutes and you've let it, half static and half country, because reaching for the dial means admitting how far you are from anything.
{
- background == "RCMP constable":
    Four days off, the first in months, spent the way you always swore you would: driving nowhere with the windows down. These are your highways. You know how empty it gets, how fast, once the [url=gloss:Sault]Soo[/url]'s lights drop off the mirror.
- background == "CSIS analyst":
    A week off, booked under protest, half gone already. You drove out of Ottawa with no plan except west and away, and it's worked: nobody within two hundred kilometres knows what you do for a living. Tonight, neither do you.
- background == "grad student":
    You finished the chapter. The actual, entire chapter. The reward was always going to be this: north of Toronto with a tent you probably won't use and a week where the only behaviour you have to code is your own.
- else:
    There's no job to be away from, which is its own kind of freedom if you say it fast. You pointed the car north of Toronto with a tank of gas and a vague plan about lakes, and the vague plan has run out with the daylight.
}
Then a sign comes up out of the dark: VACANCY, electric pink, half the tubes buzzing.
* [The vacancy sign wins.] -> WDS_090

// Checking in
=== WDS_090 ===
# id: WDS_090
# avatar: wds_night
# mode: night
~ set_header("ROADSIDE MOTEL", "Wednesday evening")
The office smells like cigarettes from twenty years back and an air conditioner that can't keep up. The clerk takes cash, gives you a key on an orange plastic diamond, room 9, and points out the ice machine without being asked.
Taped to the desk, handwritten in marker: COYOTE SIGHTINGS. DO NOT LEAVE FOOD OUT. DO NOT WALK THE TREELINE AFTER DARK.
{ background == "RCMP constable":
    There's a can of dog spray in your glovebox already. It's been there since spring.
- else:
    "They come right into the lot some nights," the clerk says, and sells you a can of dog spray off the shelf behind him. Twelve ninety-nine. You buy it mostly to end the conversation.
}
* [You take the room for the night.] -> WDS_095

// Settling in for the night
=== WDS_095 ===
# id: WDS_095
# avatar: wds_night
# mode: night
~ set_header("ROADSIDE MOTEL ROOM", "Wednesday evening")
Room 9 is brown on brown, a bedspread you choose not to think about, an air conditioner with two settings: off and labouring. Somebody's TV comes through the wall, a laugh track with the jokes filtered out.
You get a chocolate bar from the vending machine and eat it on top of the covers, watching truck headlights sweep the ceiling. This is either the loneliest you've felt all year or the most relaxed. You decide not to push on which.
Lights out.
* [Night settles over the motel.] -> WDS_100

// Two hundred clicks from anywhere
=== WDS_100 ===
# id: WDS_100
# avatar: wds_night
# mode: night
~ set_time("laterNight")
~ set_header("ROADSIDE MOTEL ROOM", "Wednesday night")
You surface sometime after two, no reason, the way you do in strange beds.
The room is striped orange where the vending machine's glow gets through the curtain gap. The air conditioner has cycled off. There's one car on the highway every few minutes, a long approach, a long fade.
Two hundred clicks from anywhere. You lie there with your eyes closed, nearly asleep again, when the quiet outside changes.
* [Something is outside.] -> WDS_105

// Something outside
=== WDS_105 ===
# id: WDS_105
# avatar: wds_night
# mode: night
~ set_header("ROADSIDE MOTEL ROOM", "Wednesday night")
A door opens somewhere along the row. Then another one. No voices go with them.
Then gravel: footsteps, several sets, slow. People are moving around out there at half past two without saying one word to each other.
You get up and put an eye to the curtain gap.
Three doors stand open along the row, lamplight spilling out of one. Six or seven people are out on the court in nightclothes and less. Nobody is talking. Nobody is hurrying.
* [You look toward the ice machine.] -> WDS_110

// The ice machine
=== WDS_110 ===
# id: WDS_110
# avatar: wds_night
# mode: night
~ set_header("MOTEL COURT", "Wednesday night")
Straight across the court from your window is the ice machine, and everything looks like evidence under its cold white light. You watch through the curtain gap, one eye, your forehead against the glass.
There's a woman crouched in that light, naked from the waist down, slacks kicked off into the gravel, underwear hanging off one ankle. She's got a cold can from the vending machine in both hands and she's grinding herself down onto it, trying to get it inside her. She's soaked. You can see the shine of it from across the court, running down the insides of her thighs, and the can keeps slipping in it, too wide to go. Every time it slips she whimpers, a high, cheated sound, close to crying, and lines it up and tries again.
She doesn't see you. She doesn't see anything.
She's going to hurt herself trying.
[i]What the fuuuuuuuuuuuck.[/i]
* [The whole court is wrong.] -> WDS_115

// The whole court
=== WDS_115 ===
# id: WDS_115
# avatar: wds_night
# mode: night
~ set_header("MOTEL COURT", "Wednesday night")
You open your door. The night is blood-warm, and the court is full of people getting out of their clothes.
A man in his fifties stands by the soda machine, barefoot, working his shirt buttons with slow drunk focus. A couple sways against a parked pickup, mouths together, his hand down the front of her shorts, and the sounds they're making don't change when your door creaks. Two more cross the end of the row holding hands, walking like the gravel isn't sharp, toward the dark end of the lot.
They're all drifting the same direction. Away from the light.
* [Then you smell it.] -> WDS_120

// The smell — # check protocol knot
=== WDS_120 ===
# id: WDS_120
# avatar: wds_night
# mode: night
# check: composure 2d6 7
~ set_header("MOTEL COURT", "Wednesday night")
Then the air moves and you get it full in the face.
Wet dog. Under that, something ranker: rut, oil, an animal smell with sex in it. It coats the back of your throat and stays.
And your body answers. Heat drops straight down through you, nipples tightening against your shirt, a throb starting up between your legs. A second behind it comes the thought, in your own voice, reasonable as anything: maybe just watch for a minute.
{ check_passed:
    You grab the doorframe and hold on, and the worst of it passes. Your head stays yours. The throb doesn't leave. You file both facts: whatever is wrong with these people came in on the air.
    * [You look for the source.] -> WDS_125
- else:
    It rolls over you, and for a few seconds you just stand in it, lips parted, breathing deeper on purpose. Your hand is at the waistband of your shorts before you know it's moved. You stop the hand. It takes longer than it should.
    * [You force yourself to look for the source.] -> WDS_125
}

// At the edge of the light
=== WDS_125 ===
# id: WDS_125
# avatar: wds_night
# mode: night
~ set_header("MOTEL COURT", "Wednesday night")
It's pacing the far edge of the lot, just past where the light ends, back and forth on all fours.
Your eyes keep trying to make it a bear: the bulk, the hair. Then it rises onto two legs without effort, the way no bear stands, and the shape under all that matted hair is a man's. Seven feet of it, easy. Naked. The pelt runs thick down its shoulders and spine, worn to bare skin at the throat and hips, and the skin is shining with sweat.
Its cock hangs half-hard from the hair at its groin, longer than your forearm and thicker than your wrist, swaying as it walks, drooling pre-cum in a rope that doesn't break, a wet thread swinging from the head to the gravel when it turns. Its balls are heavy as fists. The smell is pouring off all of it.
Two of the guests have already drifted within arm's reach. It moves past them like they're not there.
You don't reason your way to it. You know the second you see it stand: that is not a man.
* [You track what changes around it.] -> WDS_130

// The smell is doing it — # check protocol knot
=== WDS_130 ===
# id: WDS_130
# avatar: wds_night
# mode: night
# check: academic/streetwise 2d6 7
~ set_header("MOTEL COURT", "Wednesday night")
The couple at the pickup has stopped kissing. They're both facing the dark end of the lot now, swaying where they stand. The barefoot man has stopped moving at all.
You make yourself look at it as a layout. The closer a person stands to the dark end, the further gone they are. The man nearest the trees was first out and is worst off. You, in your doorway, furthest upwind: still thinking. Mostly.
{ check_passed:
    ~ wds_vector_reasoned = true
    It lines up all at once. The gradient runs with distance, and distance means concentration. The smell is doing it. It's coming off that thing, it's in the air, and the air is the whole problem. Cover your mouth. Stay upwind. Pull them off the source. You sat through WHMIS twice and hated it both times. Apparently it took.
    * [Your own body is still breathing it.] -> WDS_135
- else:
    You don't reason it out. You trip over it: turning away to cough, you notice the fog thin. Face forward, fog back. It takes three tries before you trust what that means. The smell. It's the smell doing it.
    * [Your own body is still breathing it.] -> WDS_135
}

// Her own body — # check protocol knot
=== WDS_135 ===
# id: WDS_135
# avatar: wds_night
# mode: night
# check: composure 2d6 8
~ set_header("MOTEL COURT", "Wednesday night")
Knowing doesn't stop it working.
Your shirt has started to feel wrong, collar tight, fabric dragging at your nipples with every breath. Your fear is going quiet, and the quiet feels good. And under it all, low and patient, the pull: the couple at the truck has room for a third, says some part of you that has never once talked like that.
{ check_passed:
    You bite the inside of your cheek until your eyes water, and the pain cuts through the fog. Still here. Still yours. You keep your breathing shallow and you get moving, because every minute in this air costs you.
    * [You decide what kind of person you are in this lot.] -> WDS_140
- else:
    ~ wds_deep_failed = true
    You've taken four steps toward the pickup before you understand that you're walking. Your fingers are at your collar, and the top button is already open. You bite your cheek hard enough to taste blood and drag yourself back to your door, and the whole way, part of you is still pulling the other direction.
    * [You catch yourself and decide what kind of person you are in this lot.] -> WDS_140
}

// Run or stay
=== WDS_140 ===
# id: WDS_140
# avatar: wds_night
# mode: night
~ set_header("MOTEL COURT", "Wednesday night")
Your keys are in your jacket. The car is eight spots down, upwind. You could be on the highway in under a minute, windows shut, and tonight would turn into a story you never tell because nobody would believe it.
Behind you, the woman at the ice machine whimpers again.
By morning these people will have followed that thing into the trees, or done worse to themselves in the gravel. Nobody here is coming back on their own, and there's nobody else awake to care.
* [You run for the car.]
    You run for it. Gravel, keys, door, locks, and your hand on the ignition.
    Through the windshield you can see the whole court in the vending light: the swaying couple, the barefoot man, the woman at the ice machine still working at the can, still crying. Strangers. Nobody you owe a thing.
    Your hand won't turn the key.
    * * [You get back out of the car.] -> WDS_145
* [You stay and get them clear.] -> WDS_145

// Something over her face
=== WDS_145 ===
# id: WDS_145
# avatar: wds_night
# mode: night
~ set_header("MOTEL COURT", "Wednesday night")
Filter first.
The smell has a grease to it; you can feel it filming the back of your throat, and grease means water won't stop it. Wet cloth will slow it down. Slow is what's on offer.
You duck back into your room and run the bathroom tap cold. The plan is simple enough to do with shaking hands: fold the cloth in three, soak it through, wring it once, tie it over your nose and mouth with the knot at the back of your skull. Breathe through the wet.
* [You soak a towel under the tap.] -> WDS_150
* [You soak your shirt.] -> WDS_150
* [You use the ice-bucket water.] -> WDS_150

// What she's got
=== WDS_150 ===
# id: WDS_150
# avatar: wds_night
# mode: night
~ set_header("MOTEL COURT", "Wednesday night")
The wet cloth sits tight over your nose and mouth, and every breath comes through it cold and slow. It helps. It doesn't help enough; the grease in the air is still getting in at the edges.
The dog spray can is small and dense and fits your fist. One can, one thumb, a lot of dark. You want something else in your other hand:
* [You pair the spray with the car horn and headlights.] -> WDS_155
* [You pair the spray with the fire extinguisher.] -> WDS_155
* [You keep the tire iron in your other hand.] -> WDS_155

// Driving them back
=== WDS_155 ===
# id: WDS_155
# avatar: wds_night
# mode: night
~ set_header("MOTEL COURT", "Wednesday night")
The couple at the pickup is closest to the dark end, so they're first.
"Hey. HEY." Nothing. Their faces are aimed at the treeline. You turn your own face aside and put a half-second burst of dog spray across both of them.
The sound they make is the worst part. Not anger. Grief. They fold up coughing and you grab the woman's arm and haul, and she fights you the whole way to her door, crying, reaching back toward the dark like you're the one hurting her. You are the one hurting her.
You do it again at the next door. And again. You're crying too, somewhere in there. It doesn't slow you down.
* [The source is still at the edge of the light.] -> WDS_160

// Driving it off — # check protocol knot
=== WDS_160 ===
# id: WDS_160
# avatar: wds_night
# mode: night
# check: composure/confrontation 2d6 9
~ set_header("MOTEL COURT", "Wednesday night")
It has come up the lot. Maybe because you took its people away.
Twenty feet, fifteen, head low, on all fours. This close the smell comes straight through the wet towel, and your body starts agreeing with it again, fear thinning out, warmth climbing.
You get the can up.
{ check_passed:
    ~ wds_spine_held = true
    Your legs want to stay put and let it come. You make them hold for a better reason: range. You let it close to where you cannot miss, thumb on the tab, arm level, and you empty the charge into its eyes and nose.
    * [It breaks away from the light.] -> WDS_165
- else:
    ~ wds_spine_failed = true
    At ten feet the fear shuts off like a tap, and what floods in behind it is warm and slow and interested. Your arm starts to drop. Some part of you is measuring its hands, its mouth, the weight of it, and approving.
    Your thumb remembers the plan anyway. The spray catches it across the eyes and muzzle.
    * [It breaks away from the light anyway.] -> WDS_165
}

// Into the dark
=== WDS_165 ===
# id: WDS_165
# avatar: wds_night
# mode: night
~ set_header("MOTEL COURT", "Wednesday night")
{ not wds_influence_granted:
    ~ temp wds_influence = 2
    { wds_deep_failed or wds_spine_failed:
        ~ wds_influence = 3
    }
    ~ adjust_influence(wds_influence)
    ~ wds_influence_granted = true
}
{ not wds_skill_granted:
    {
    - wds_vector_reasoned:
        ~ grant_skill("academic", 1)
    - wds_spine_held:
        ~ grant_skill("composure", 1)
    - else:
        ~ grant_skill("streetwise", 1)
    }
    ~ wds_skill_granted = true
}
It screams like a kicked dog, deeper than any dog could go, and goes backward off its feet, pawing at its face.
Then it runs. Low, fast, on all fours, across the gravel margin and the dead grass, out past the reach of the highway light. Branches, then nothing.
The lot stands quiet. The vending machine buzzes. Your towel is down around your neck, and you don't know how long ago that happened.
* [The guests begin coming back.] -> WDS_170

// Coming back
=== WDS_170 ===
# id: WDS_170
# avatar: wds_night
# mode: night
~ set_header("MOTEL COURT", "Wednesday night")
It lets go of them in ones and twos.
The barefoot man looks down at his own chest and starts to shake. The couple you sprayed sit apart against the pickup's tire, eyes streaming, not talking. A heavyset man you never saw go under comes back from the dark end at a walk that keeps trying to be a run, fly open, feet bleeding.
By the ice machine the woman has stopped trying. She sits in the gravel with her slacks held against her front, crying in long low pulls, and when you crouch down beside her she says, "I don't. I don't. I don't."
The smell is still on everything.
* [Someone has to make the call.] -> WDS_175

// Someone has to call this in
=== WDS_175 ===
# id: WDS_175
# avatar: wds_night
# mode: night
~ set_header("ROADSIDE MOTEL", "Wednesday night")
The office phone smells like the office. {background == "RCMP constable": You call your own detachment, because you know exactly how this is going to sound, and it should sound that way to someone who knows you.|You call 911 and listen to yourself try to build the sentence. A man. An animal. Big. The smell, you keep saying, as if that helps.}
The [url=gloss:OPP]OPP[/url] cruiser takes forty minutes. By then the guests have statements that contradict each other and themselves, and you have the only account with a beginning, a middle, and an end. There's hair snagged on the corner of the soda machine. Prints in the soft ground past the gravel, too wide, too long. And your clothes, which still smell like it.
* [The smell does not wash out cleanly.] -> WDS_180

// She can still smell it
=== WDS_180 ===
# id: WDS_180
# avatar: wds_night
# mode: night
~ set_header("ROADSIDE MOTEL", "Wednesday night")
You shower until the hot water quits. It's in your hair anyway. Faint, under the motel soap, but there: wet dog, rut, oil.
What you keep coming back to, sitting on the end of the bed, isn't the thing itself. It's how good the fear felt going quiet. Something got into you through the air, through nothing, through breathing, and your body took its side.
You sleep with the window shut and the air conditioner roaring. You check the lock twice.
* [Days later, the file has a smell in it.] -> WDS_200

// Occurrence report — Branch file extract STUB (native scene template later)
=== WDS_200 ===
# id: WDS_200
# screen: menu
# scene: branch_file_extract
# extract: wds_occurrence_report_03_ONT_0820
~ set_date(2003, 8, 25, "morning")
~ set_header("BRANCH FILE EXTRACT", "Monday morning")
Incident File 03-ONT-0820, extract. Rendered by the native BranchFileExtract scene template; this knot is a placeholder.
* [You turn the page.] -> WDS_205

// Recommendation — Branch file extract STUB (native scene template later)
=== WDS_205 ===
# id: WDS_205
# screen: menu
# scene: branch_file_extract
# extract: wds_recommendation_r_flett
~ set_header("BRANCH FILE EXTRACT", "Monday morning")
Recruitment Recommendation, R. Flett, 2003.08.25. Rendered by the native BranchFileExtract scene template; this knot is a placeholder.
* [The file closes.]
    // TODO(runtime): native CC-500 handoff sets inciting_incident to "Wet Dog Smell"
    ~ set_date(2005, 9, 12, "morning")
    -> wds_end

// Native-scene handoff — original twee target(s): CC-500 Summary.
=== wds_end ===
# id: wds_end
The wds sequence ends here; the runtime hands off to the native scene (CC-500 Summary).
-> END

